### ISSUE TITLE
`language-id` not changing after the first file

### ISSUE THREAD

**Issue by minikN** [joaotavora/eglot#1384]
When working with a project that is supposed to have different language-ids for different file types (I test it with a js CRA application) eglot seems to send the correct `language-id` for the first file I open, but doesn't change it accordingly if I open a file of a different type afterwards (unless I'm misunderstanding the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentItem) and this isn't suppose to happen anyway).

I am aware of commit 2fbcab293e and tried to configure eglot correctly in two ways:

1. I evaluated
```lisp
(add-to-list 'auto-mode-alist '("\\.js\\'" . js-mode))
(add-to-list 'auto-mode-alist '("\\.jsx\\'" . js-jsx-mode))

(put 'js-mode 'eglot-language-id "javascript")
(put 'js-jsx-mode 'eglot-language-id "javascriptreact")

(with-eval-after-load
    'eglot
  (add-to-list
   'eglot-server-programs
   '((js-mode js-jsx-mode) .
  ("/gnu/store/928xbf54h864yz55j90m29f09l5bkp07-node-typescript-language-server-0.11.1/bin/typescript-language-server" "--stdio" :initializationOptions
  (:tsserver
   (:path "/gnu/store/807nkysq2myq6dgb3fsa0padsbin5rl0-node-typescript-4.7.3/lib/node_modules/typescript/lib"))))))
```
```
(get 'js-mode 'eglot-language-id) => "javascript"
(get 'js-jsx-mode 'eglot-language-id) => "javascriptreact"
```
Then Iopened `App.js` of the CRA project, in events buffer I can see `languageId` being set to `javascript`. If I open another file `Test.jsx` afterwards, in the new `textDocument/didOpen` event I also see `languageId` being set to `javascript`, but it should be `javascriptreact` in this case.

2. I also tried evaluating (I restarted emacs before trying this)
```lisp
(add-to-list 'auto-mode-alist '("\\.js\\'" . js-mode))
(add-to-list 'auto-mode-alist '("\\.jsx\\'" . js-jsx-mode))

(with-eval-after-load
    'eglot
  (add-to-list
   'eglot-server-programs
   '(((js-jsx-mode :language-id "javascriptreact")
   (js-mode :language-id "javascript")) .
  ("/gnu/store/928xbf54h864yz55j90m29f09l5bkp07-node-typescript-language-server-0.11.1/bin/typescript-language-server" "--stdio" :initializationOptions
  (:tsserver
   (:path "/gnu/store/807nkysq2myq6dgb3fsa0padsbin5rl0-node-typescript-4.7.3/lib/node_modules/typescript/lib"))))))
```
But the `languageId` I see in the events buffer are the same.

Here are two examples:
1. First `App.js`, then `Test.jsx`: http://paste.debian.net/1313114/
2. First `Test.jsx`, then `App.js`: http://paste.debian.net/1313112/
(I restarted emacs inbetween)

MRE:
1. `emacs -Q`
2. eval
```
(add-to-list 'auto-mode-alist '("\\.js\\'" . js-mode))
(add-to-list 'auto-mode-alist '("\\.jsx\\'" . js-jsx-mode))

(with-eval-after-load
    'eglot
  (add-to-list
   'eglot-server-programs
   '(((js-jsx-mode :language-id "javascriptreact")
   (js-mode :language-id "javascript")) .
  ("/gnu/store/928xbf54h864yz55j90m29f09l5bkp07-node-typescript-language-server-0.11.1/bin/typescript-language-server" "--stdio" :initializationOptions
  (:tsserver
   (:path "/gnu/store/807nkysq2myq6dgb3fsa0padsbin5rl0-node-typescript-4.7.3/lib/node_modules/typescript/lib"))))))
```
3. Open `js` file in project
4. `M-x eglot`
5. Switch to `jsx` file
6. Inspect events buffer

If I misunderstood the spec or something in eglot I apologize in advance.

Thanks.

**Comment by joaotavora** [comment]
> If I misunderstood the spec or something in eglot I apologize in advance.

No need to apologize, but you should rather refer to Emacs's commits, not this repository, because Eglot's development happens in Emacs.  

Here, I think the problem here is simply that `js-jsx-mode` *derives* from `js-mode`.  So any buffer that is in `js-jsx-mode` is -- by definition -- also in `js-mode`.  So this is ultimately question of major mode design.  

But it's also a real problem, I presume and is not an easy question to solve.  Though there are attempts to solve it.  I participated in one of those attempts with multiple ideas -- designed at more closely associating major modes with languages -- but my ideas were not accepted.  I have since abandoned those discussions, and I plan to keep doing that but I encourage you to particpate in these issues:

bug#68246 https://debbugs.gnu.org/cgi/bugreport.cgi?bug=68246
bug#68217: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=68217

I've been away from them for quite a while now (again, I plan to stay away, so please don't CC me).  @monnier had a solution ready, perhaps it will work here too.

**Comment by monnier** [comment]
IIUC the behavior comes from `eglot--languageId` where we look through
the languages supported by the current server and see if any of them is
applicable to the current buffer's mode, paying attention to
mode inheritance.

*If* the server also handles the "javascriptreact" language, than maybe
we can fix this immediate problem by refining `eglot--languageId` so it
returns "the best" language rather than the first:

```
diff --git a/lisp/progmodes/eglot.el b/lisp/progmodes/eglot.el
index 4a7c525003c..bb96d1c1af5 100644
--- a/lisp/progmodes/eglot.el
+++ b/lisp/progmodes/eglot.el
@@ -2850,10 +2850,10 @@ eglot--languageId
   "Compute LSP \\='languageId\\=' string for current buffer.
 Doubles as an predicate telling if SERVER can manage current
 buffer."
-  (cl-loop for (mode . languageid) in
-           (eglot--languages server)
-           when (provided-mode-derived-p major-mode mode)
-           return languageid))
+  (let ((languages (eglot--languages server)))
+    (cl-loop for parent in (derived-mode-all-parents major-mode)
+             when (assq parent languages)
+             return (cdr (assq parent languages)))))
 
 (defun eglot--TextDocumentItem ()
   "Compute TextDocumentItem object for current buffer."
```

OTOH if the current server doesn't handle the "javascriptreact"
language, then we're faced with a tradeoff between keep using the same
server (but with a suboptimal language) or starting a new server.
It's not even completely clear to me how to detect this situation in the
general case where different servers can use different names for "the
same" language.
