### ISSUE TITLE
Have unique `project-nickname`s

### ISSUE THREAD

**Issue by FelipeLema** [joaotavora/eglot#151]
Like buffers when they have the same name, we should be able to have a way to distinguish two projects with the same name (`dirname` of the path of the project root).

The sad side of this story is that the way is that unique naming for buffers is not re-usable AFAIK: there's `generate-new-buffer-name`, but it's fixed to check on `(buffer-list)`.

If developers are OK with having this I'll implement it myself.

**Comment by FelipeLema** [comment]
I didn't have anything in mind at first. I know there's some state to be modified, that's unavoidable. Personally I would have:

- `get-project-nickname` variable that points to opaque function that returns a name candidate (would default to `'directory-filename-dirname`
- `resolve-project-nicknames` variable that points to opaque function that receives a list of names and returns a list with the unique-ed names.
- at the end of the `eglot` command would run something like `(update-project-nicknames resolve-project-nicknames)`. This function would pass the list of each nickname and then update them in the same order. In other words: "ensure nicknames are still unique _after_ adding a new project"

**Comment by joaotavora** [comment]
> I know there's some state to be modified, that's unavoidable. 

Is it, though? In what situations in particular was the duplicate nickname problematic? 

Only after we make a list of these, can we decide if we can reserve the disambiguation for those situations, which would in theory be preferrable.

**Comment by FelipeLema** [comment]
I had two projects with nickname `src` (let's say `/home/me/repos/some-c++-repo/src` and `/home/me/repos/some-c++-repo/some-other-c++-repo/src`) and I had no way to distinguish between when using elisp commands (with `M-x`). If I wanted to `eglot-shutdown` one, I would have to cross my fingers to get the right one on the first try.

I say there's some state to be modified because you don't encounter this problem until you run `eglot` on a second project with the same `basename`. The way Emacs solves this problem with buffers is by changing the name of all the buffers with the same name (typically seen when opening several terminals).

The same issue could arise from having a single git repo cloned in different locations.

**Comment by joaotavora** [comment]
> The same issue could arise from having a single git repo cloned in different locations.

Don't worry. I understand that the issue can arise legitimately.

But instead of changing state, you could modify the printing it behaves differently when there is an ambiguity.  This is because, in eglot, different servers are easy to distinguish even if they have the same name, while two buffers in emacs _cannot_ have the same name.

So in your eglot-shutdown example, you can probably just change the `name` function in `eglot--read-server`.  

Secondly, if you also want to solve the problem in `eglot--mode-line-format` (I thing you _should_) then you need a slightly more generic solution.  Perhaps a top-level `eglot--server-unique-nickname (srv)` that also consults `eglot--servers-by-project`. In that case, obviously use that same new function in `eglot--read-server`.

Finally, if you also want to solve the problem of the events and stderr buffers (I think you should _not_ tackle this, at least not for now), then you have to change state notably the names of the aforementioned buffers.  It's unclear when this should happen, but probably in server creation and shutdown.  But let's only do this if it really becomes a problem.

**Comment by FelipeLema** [comment]
Sounds fair. It's not the state changing that worries me but the function that receives a list of `eglot-lsp-server`s and returns a list of unique nicknames (it has to find the next-to-minimum-common-path).

I'll implement this method and use it for `eglot--mode-line-format` and whatever functions require the user to choose from a list of servers (namely `eglot-shutdown`) during the next few weeks.

**Comment by joaotavora** [comment]
> (it has to find the next-to-minimum-common-path).

I don't know exactly what you mean by that. It sounds sophisticated, but I would first settle for a function that takes a server and list of servers and outputs the server's position in the list as a string, or an empty string if there's only one duplicate. Wouldn't that work?

**Comment by FelipeLema** [comment]
Ok, so now I've come to realize that each server spawns several stuff that assumes a fixed nickname and would need extra renaming (at least each stdout/stderr/event buffers). Renaming nicknames is not that difficult, but this problem could very easily scale and prove itself to be hard to maintain.

Since this looks like a lot of effort and I'm the only interested (and implementer) I'm closing this.
