### ISSUE TITLE
How to debug xref-find-definitions 

### ISSUE THREAD

**Issue by carlosdagos** [joaotavora/eglot#153]
I'm using RLS

```bash
$ rls --version
rls-preview 0.130.5 (1c755ef 2018-10-20)
```

When I try `'xref-find-definitions` I keep getting (for example):

```
user-error: No definitions found for: read_line
```

I'm using the following `rustc`:

```bash
$ rustc --version
rustc 1.32.0-nightly (9fefb6766 2018-11-13)
```

PS: I'm also new to Rust so it's quite possible that I'm missing something 😄 

Thanks!

**Comment by mkcms** [comment]
If you want to debug elisp, evaluate (`C-u C-M-x`) this function: https://github.com/joaotavora/eglot/blob/604c1b0c31f7202f83373dd97f620dbc2dddfa52/eglot.el#L1433

But instead of doing that you should look in the events buffer (`M-x eglot-events-buffer`) at calls to `textDocument/definition` method.

> When I try `'xref-find-definitions` I keep getting (for example):
> 
> ```
> user-error: No definitions found for: read_line
> ```

Looks like the server can't find definitions for this identifier, maybe your setup is wrong, e.g. project is not setup correctly. Check if `(car (project-roots (project-current)))` is the correct root of your project.

**Comment by joaotavora** [comment]
> But instead of doing that you should look in the events buffer (M-x eglot-events-buffer) at calls to textDocument/definition method.

Yeah I was going to suggest just that, but was overwhelmed with work this weekend. The events buffer is one mouse click in the eglot mode-line area away.

**Comment by carlosdagos** [comment]
Thank you both for the help.

When I checked `(car (project-roots (project-current)))`, it seems the project was setup okay (got the root folder of the project).

I looked at the events buffer and nothing seemed out of the ordinary in terms of setup/config -- of course when I tried `M-.` I got 

```
(:jsonrpc "2.0" :id 298 :result
          [])
```

However, now it's working (most of the time). One thing I did recently was change my rust installation from Nix to the [documented way](https://rustup.rs/), and this seems to have solved the issue. I don't know _what_ about the Nix installation would cause issues, but it seems that's not an issue for this repo 😄 

Cheers
