### ISSUE TITLE
Error thrown when eglot called from hook

### ISSUE THREAD

**Issue by ar1a** [joaotavora/eglot#17]
Hiya! I was trying to setup eglot like so:
```
(def-package! eglot
  :commands (eglot)
  :when EMACS26+
  :init
  (add-hook 'python-mode-hook #'eglot)
  :config
  (set! :company-backend 'eglot--managed-mode '(company-capf)))
```
Yet whenever I open a python file, this error is thrown:
```
Debugger entered--Lisp error: (wrong-number-of-arguments (4 . 5) 0)
  eglot()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook python-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook python-mode-hook))
  run-mode-hooks(python-mode-hook)
  python-mode()

```

Funnily enough, once that error pops up, M-x eglot works fine.
This also happens in sh-mode, and that's the only other mode I've tested.

**Comment by joaotavora** [comment]
Hi. I know what you're trying to do, and it's a good idea, but there's currently no clean way to do it.

> Funnily enough, once that error pops up, M-x eglot works fine.

That's because there's a difference between calling a function *interactively* like `M-x something` (or by pressing a key bound to `something`) and calling it from a lisp program, as is the case when you add things to a hook. The latter normally passes no arguments to the function, while the former collects arguments from the environment (in this case 5 of them) and gives them to the function.

So what you need is a function of no arguments that you can add to the hook.  It's not, and will never be `eglot`, but we can think about some function say `eglot-try-to-connect` or `eglot-ensure` or `eglot-or-die` that fits that bill.

I'm unsure about the name because I'm not sure about the semantics. What should happen if there's no suitable LSP server to start, or something goes wrong. Do you want to get an error or should it just fail silently? I have to think about this, in the meantime you can try

```
(add-hook 'python-mode-hook (lambda () (unless eglot--managed-mode (call-interactively 'eglot))))
```

which I absolutely did not test, so no warranty.

**Comment by ar1a** [comment]
I got away with it like so:
```
  (add-hook! 'python-mode-hook (unless (bound-and-true-p eglot--managed-mode)
                                 (call-interactively #'eglot)))
```
You have to check if it's bound first, because M-x eglot lazy loads the file, but eglot--managed-mode the first time will be void.

Once you open another file in the project though, it asks if you want to reconnect to the process. I even tried appending the hook instead, but alas no such luck.

**Comment by joaotavora** [comment]
> (add-hook 'python-mode-hook (lambda () (unless eglot--managed-mode (call-interactively 'eglot))))

Never mind, that won't work.

**Comment by joaotavora** [comment]
(oh you just commented, what a coincidence)

> Once you open another file in the project though, it asks if you want to reconnect to the process. I even tried appending the hook instead, but alas no such luck.

yeah, I have to rework that.

**Comment by ar1a** [comment]
I also have some issues with javascript and eglot, although i think it may be issues with my configuration. I'll poke around in it another time.

**Comment by joaotavora** [comment]
Right, so `(add-hook 'foo-mode-hook 'eglot-ensure)` should do what you want.

Let me know if it works (and those js issues maybe)
