### ISSUE TITLE
Mode hook for eglot?

### ISSUE THREAD

**Issue by casouri** [joaotavora/eglot#182]
Is there a hook like other major/minor mode hooks for eglot?

I looked into `eglot-connect-hook` but 1) it passes arguments into functions in hook, that's not good in some cases 2) Is it supposed to be used as a mode hook for eglot? I.e., get called when eglot is enabled. Or it has other purposes?

**Comment by joaotavora** [comment]
There is no explicit user-visible mode-hook for Eglot right now, because I haven't yet decided on what the desired semantics of that hook should be.  There is, though, an internal `eglot--managed-mode-hook` call when eglot starts managing a file buffer and when when it stops managing a file buffer.  I am not 100% convinced that it should be made public, but maybe you can help there if you explain what "other purposes" you see it used for.

**Comment by casouri** [comment]
I want the mode hook to enable `eldoc-box-hover-mode`. But I'm happy with `eglot--managed-mode-hook`. Maybe you can consider a public one when someone else asks for it for a good reason.

>Or it has other purposes?

I mean if `eglot-connect-hook` has some special purpose so that it should not be used as a general mode hook (to enable stuff when eglot is enabled).

Feel free to close this. I have what I need now : P

**Comment by joaotavora** [comment]
Let's not close this.  I still haven'tmade eglot-managed-mode-hook public

**Comment by nverno** [comment]
Bump.  I think it would be useful to disable/remove hooks for capf/eldoc/imenu/etc. that aren't configurable.
