### ISSUE TITLE
Disable sorting in eglot--handling-xrefs

### ISSUE THREAD

**Issue by nemethf** [joaotavora/eglot#220]
Hi João,
 
I'm experimenting with my own language server, which returns the references in the order of relevance.  Would it be possible to disable the sorting part of eglot--handling-xrefs and keep order determined by the server?  Obviously, the current implementation makes sense for most of the language servers, so this should be configurable somehow.

Thank you

**Comment by joaotavora** [comment]
Hi Felicián,

Just wanted to comment very quickly that I'm not married with the current sorting by location line: I think it should be the server that decides on an order and Eglot should respect it.  The grouping by file is another matter, but even so it can keep the relative order unchanged within a group.

So you can propose something that breaks this line-ordering and will see what the effect is on most language servers (i.e. if the sorting order stops making sense completely).

Anything more than that should be added to the LSP standard, since it is really something that makes sense there, not in an customizable option in the editor.

**Comment by nemethf** [comment]
I assume eglot sorts the references because some servers send them unordered.  On the other hand, clients shouldn't reorder references coming from my experimental server.  So I agree the standard should be more specific or there should be a new server capability in which servers can hint how the clients should handle the references.

I can try to lobby for modifying the protocol but it would help me if you could describe why you implemented the sorting algorithm.  Which are those servers who send references in wrong order? 

However, the process of extending the protocol might take long and the outcome is uncertain.  I'd like to implement an experimental extension in eglot-x and my server in the mean time.  However, it is not easy to override the current behavior with an advice because the sorting algorithm defined in a lambda function inside a defmacro.  Can you name the function or change the defmacro to defun?

Thanks again.

**Comment by joaotavora** [comment]
> However, the process of extending the protocol might take long and the outcome is uncertain.

yes certainly.

> Can you name the function or change the defmacro to defun?

I can do that, but I would just like to hear what @mkcms has to say.  He added the sorting back in September, but frankly I would just remove it.

**Comment by MaskRay** [comment]
AFAIK the specification does not say returned `Location[]` or `LocationLink[]` are grouped by `uri: DocumentUri;` (filenames) but for exhibition purposes the client may need to group them. The returned `Location[]` or `LocationLink[]` may be sorted by relevance or by filename/line pairs.

Since eglot implements the backends (`xref-backend-definitions` ...), not the xref.el UI, deleting the sorting looks good to me. The sorting can be done in the UI layer (ivy-xref helm-xref) if needed.

**Comment by nemethf** [comment]
In my case, the problem was that only the server knew how to sort references according to relevance.  However, things happen slowly here, and that can be a good thing, because in the mean time I realized I can circumvent my original problem by partitioning my "references"  into definition, typeDefinition, implementation, and references.  (Eglot seems to support definition and references only, isn't it?)

I hope eglot would provide nice support for references even without ivy and helm.  Also, I haven't really used a "jump to references" function during a normal programing session, but I think sometimes it might be useful to sort the references according to the recently visited buffers, which the language server cannot do.

**Comment by mkcms** [comment]
> I can do that, but I would just like to hear what @mkcms has to say. He added the sorting back in September, but frankly I would just remove it.

I added it because I found the behavior very annoying with some servers I was using at the time, it seemed like they returned the locations in completely random order. Personally I prefer it sorted, but I can also see why sometimes it's better to have the server choose the order. 

I suppose it makes sense to convert the macro into a defun, or to disable sorting altogether (but preferably give users a way, even hacky, to enable it)

**Comment by joaotavora** [comment]
> I added it because I found the behavior very annoying with some servers I was using at the time

Any idea what those were?

> I suppose it makes sense to convert the macro into a defun, or to disable sorting altogether (but preferably give users a way, even hacky, to enable it)

I think I'm going to disable it by default, but as suggested, make it a function somewhere so that demanding users can `add-function` around it. Technically, I _think_ the feature to sort references by line number should be `xref.el`, but I'd rather not bother @dgutov yet again (oops :-))

**Comment by mkcms** [comment]
> Any idea what those were?

Sure, I mainly use clangd and pyls for work, so it must have been one of those. Maybe since then they changed their behavior, though.

**Comment by dgutov** [comment]
> Technically, I _think_ the feature to sort references by line number should be `xref.el`

If it were there, you wouldn't be able to disable it, would you?

**Comment by joaotavora** [comment]
> If it were there, you wouldn't be able to disable it, would you?

Depends on how you implement it, right? You could stash the references in original order somewhere in the `*xref*` buffer's local variable and sort a copy, then let the user (or the client program) toggle.  

But as I said, I don't think this is very urgent: LSP servers should care a little bit more about sorting.
