### ISSUE TITLE
Another "wrong number of arguments" issue using straight.el

### ISSUE THREAD

**Issue by karljs** [joaotavora/eglot#231]
On a fresh install of Eglot (using straight.el instead of the default package.el). I open a Haskell file in my project, run `M-x eglot`, and get `error in process filter: Wrong number of arguments: (5 . 5), 6`.  I've seen several issues related to this, but all of them seem to be for old versions of Emacs.  I'm using 26.1 and the old issues suggest I shouldn't be seeing this anymore.  

This seems to be related to flymake, but I believe I have the latest version from elpa (which is mirrored by straight at https://github.com/emacs-straight/flymake

If this is a problem with straight.el I will gladly move the bug report there.

If I `toggle-debug-on-error` I get the following:
```
Debugger entered--Lisp error: (wrong-number-of-arguments (5 . 5) 6)
  eglot--make-diag(#<buffer GSN.hs> 1 40 eglot-error "ghcmod: " ((eglot-lsp-diag :severity 1 :range (:start (:line 0 :character 0) :end (:line 1 :character 0)) :source "ghcmod" :message "")))
  #f(compiled-function () #<bytecode 0x14ea819>)()
  eglot--call-with-interface((Diagnostic (:range :message) (:severity :code :source :relatedInformation)) (:severity 1 :range (:start (:line 0 :character 0) :end (:line 1 :character 0)) :source "ghcmod" :message "") #f(compiled-function () #<bytecode 0x14ea819>))
  #f(compiled-function (arg1 arg2 &rest rest) "Handle notification publishDiagnostics" #<bytecode 0x10bfb9d>)(#<eglot-lsp-server eglot-lsp-server> textDocument/publishDiagnostics :uri "file:///home/karl/work/jitcert/ideas/exploratory-dsl/src/JitCert/GSN.hs" :diagnostics [(:severity 1 :range (:start (:line 0 :character 0) :end (:line 1 :character 0)) :source "ghcmod" :message "")])
  apply(#f(compiled-function (arg1 arg2 &rest rest) "Handle notification publishDiagnostics" #<bytecode 0x10bfb9d>) #<eglot-lsp-server eglot-lsp-server> (textDocument/publishDiagnostics :uri "file:///home/karl/work/jitcert/ideas/exploratory-dsl/src/JitCert/GSN.hs" :diagnostics [(:severity 1 :range (:start (:line 0 :character 0) :end (:line 1 :character 0)) :source "ghcmod" :message "")]))
  #f(compiled-function (arg &rest args) #<bytecode 0x14ea4a1>)(#<eglot-lsp-server eglot-lsp-server> textDocument/publishDiagnostics :uri "file:///home/karl/work/jitcert/ideas/exploratory-dsl/src/JitCert/GSN.hs" :diagnostics [(:severity 1 :range (:start (:line 0 :character 0) :end (:line 1 :character 0)) :source "ghcmod" :message "")])
  apply(#f(compiled-function (arg &rest args) #<bytecode 0x14ea4a1>) #<eglot-lsp-server eglot-lsp-server> textDocument/publishDiagnostics (:uri "file:///home/karl/work/jitcert/ideas/exploratory-dsl/src/JitCert/GSN.hs" :diagnostics [(:severity 1 :range (:start (:line 0 :character 0) :end (:line 1 :character 0)) :source "ghcmod" :message "")]))
  eglot-handle-notification(#<eglot-lsp-server eglot-lsp-server> textDocument/publishDiagnostics :uri "file:///home/karl/work/jitcert/ideas/exploratory-dsl/src/JitCert/GSN.hs" :diagnostics [(:severity 1 :range (:start (:line 0 :character 0) :end (:line 1 :character 0)) :source "ghcmod" :message "")])
  apply(eglot-handle-notification #<eglot-lsp-server eglot-lsp-server> textDocument/publishDiagnostics (:uri "file:///home/karl/work/jitcert/ideas/exploratory-dsl/src/JitCert/GSN.hs" :diagnostics [(:severity 1 :range (:start (:line 0 :character 0) :end (:line 1 :character 0)) :source "ghcmod" :message "")]))
  #f(compiled-function (server method params) #<bytecode 0x14a5abd>)(#<eglot-lsp-server eglot-lsp-server> textDocument/publishDiagnostics (:uri "file:///home/karl/work/jitcert/ideas/exploratory-dsl/src/JitCert/GSN.hs" :diagnostics [(:severity 1 :range (:start (:line 0 :character 0) :end (:line 1 :character 0)) :source "ghcmod" :message "")]))
  jsonrpc-connection-receive(#<eglot-lsp-server eglot-lsp-server> (:jsonrpc "2.0" :params (:uri "file:///home/karl/work/jitcert/ideas/exploratory-dsl/src/JitCert/GSN.hs" :diagnostics [(:severity 1 :range (:start (:line 0 :character 0) :end (:line 1 :character 0)) :source "ghcmod" :message "")]) :method "textDocument/publishDiagnostics"))
  jsonrpc--process-filter(#<process EGLOT (jitcert/haskell-mode)> "Content-Length: 287\015\n\015\n{\"jsonrpc\":\"2.0\",\"params\":{\"uri\":\"file:///home/karl/work/jitcert/ideas/exploratory-dsl/src/JitCert/GSN.hs\",\"diagnostics\":[{\"severity\":1,\"range\":{\"start\":{\"line\":0,\"character\":0},\"end\":{\"line\":1,\"character\":0}},\"source\":\"ghcmod\",\"message\":\"\"}]},\"method\":\"textDocument/publishDiagnostics\"}")
```

**Comment by joaotavora** [comment]
I have to say: I don't get "straight". It's so straight, so straight that it doesn't install dependencies properly.  Sounds kinda useless as a package manager...

Anyway, as you have discovered, you have to install a newer `flymake.el` as a dependency: it's in GNU ELPA, as you have discovered, and version 1.0.5 is required. `package-install` or `package-list-packages` should take care of this for you.  But you can download the file from Emacs master and place it somewhere in your load-path, or somehow convince straight to be a little less straight, there's nothing wrong with that.

> If this is a problem with straight.el I will gladly move the bug report there.

I have no idea, but I don't want to try and find out.  There's a reason Eglot doesn't require anything but Emacs: it's also so that it doesn't have to support anything but Emacs. If there's something missing in eglot.el from that point of view, I'd love to hear about it.  Otherwise my advice would be: don't use "straight".

Oh and sorry for the rant :-)

**Comment by karljs** [comment]
@joaotavora Thanks for the explanation (and the package).  Straight does a nice job of letting me manage forks, packages not on melpa, etc. so the extra effort has been worth it for me, but that's probably just a factor of my workflow.  I'll file a bug there instead, since this issue is specific to that tool.

**Comment by joaotavora** [comment]
Hi @karljs, I manage forks and git checkouts too, just use normal `load-path`:
```
(dolist (dir (directory-files "~/Source/Emacs" t "^[^.]"))
  (when (file-directory-p dir) (add-to-list 'load-path dir)))
```

Now just `(require 'mypackage`) or better `(require 'mypackage-autoloads)`, use `with-eval-after-load` to configure it (no `use-package` needed). If the package in question doesn't support these tried-and-tested methods of configuration, you probably shouldn't be using it anyway!  Anyway, this is just my two cents: it pays to have a simple `.emacs` instead of a "next-generation" package manager.
