### ISSUE TITLE
xref-find-definitions identifies the wrong fn definition

### ISSUE THREAD

**Issue by j0ni** [joaotavora/eglot#246]
I'm not sure how to debug this, would appreciate some advice.

I have a rust project, created and managed with cargo. When I select one function after eglot has finished doing its indexing (I assume that's what's going on), the fn at point is highlighted and some documentation appears in the minibuffer/echo area. In my case, internal functions are not yet documented, so I just see the declaration.

When I select library functions or functions from other crates, it correctly identifies the function in the minibuffer/echo area, and I can `M-.` through to the definition. However, when I select internal functions from another module, the function identified is the one defined immediately before the correct definition.

So given the following defs:

```rust
    fn generate_candidates(&mut self) {
      // ...
    }

    pub fn create_models_for_contact(&self, skip_virtual_successes: bool) {
      // ...
    }

    pub fn choose_hours(self) -> (i64, i64) {
      // ...
    }
```
In client code, if I `M-.` on `create_models_for_contact`, I see and am taken to `generate_candidates`. Similarly, if I select `choose_hours`, I see and am taken to the `create_models_for_contact` definition.

I should note that I'm using a fairly fresh build of emacs 27.0.50, maybe a day or two old.

_update to add_: there was a bug in `create_models_for_contact` which caused Flymake errors. Once I removed the code with the errors, indexes were quickly rebuilt correctly and everything now works. I'm leaving this open because it seems like it is still not right, though not as much of a problem for me as I had thought. I think it should fail differently if it fails, but I'm not entirely sure how.

**Comment by nemethf** [comment]
You might try to open the incorrect file (with Flymake errors), enable eglot (M-x eglot), wait for the indexing to finish, execute `M-.` over the problematic point, and then switch to the `*EGLOT (...) events*` buffer. Looking at the buffer's content is a good way to identify whether the issue is on the client's or on the server's side.

**Comment by j0ni** [comment]
I wasn't sure what I was seeing, but this might help?

```
client-request (id:59) Wed Apr  3 20:44:42 2019:
(:jsonrpc "2.0" :id 59 :method "textDocument/documentHighlight" :params
          (:textDocument
           (:uri "file:///home/joni/Scratch/TheGuild/Motiva/optimized-scheduler/src/main.rs")
           :position
           (:line 26 :character 20)))

server-reply (id:58) Wed Apr  3 20:44:42 2019:
(:jsonrpc "2.0" :id 58 :result
          (:contents
           [(:language "rust" :value "fn generate_candidates(&mut self)")]))
```
note that the line I was on was actually line 27. The first line has a `#![allow(dead_code)]` macro on it, if that is relevant to the off-by-one thing. Unless it's somehow 0-based in this context.

Note that point was positioned on the `create_models_for_contact` call, and `generate_candidates` isn't public.

**Comment by nemethf** [comment]
The off-by-one thing happens because the protocol and emacs count lines differently.  However, the id of a reply should echo back the id of the request, so what you wrote is not a request-reply pair.

If I understand you correctly,  `M-.` behaves strangely, so you should search for requests with "textDocument/definition" and the corresponding replies. 

(I guess we'll see that the server sends an incorrect location and eglot jumps to this incorrect location.  So, probably, the next question is whose fault is that.   If you open the file with errors and don't edit it at all, just press M-. at the right location, and the server still sends an incorrect location, then the bug is most probably on the server's side.  But we need to see the logs first.)

**Comment by j0ni** [comment]
That careless paste was from last night while I was attempting to figure this out. After leaving the comment this morning I have restarted emacs, and now I cannot reproduce it - even with the bugs in the target file reintroduced, in a freshly started emacs, eglot correctly displays the fn name in the echo area and takes me there when I `M-.`.

If this arises again, I will re-open this issue and paste the logs as you asked. I agree that this seems more likely to be an `rls` snafu than a problem with eglot.

Thanks @nemethf for your patience and explanations.
