### ISSUE TITLE
Applying TextEdits fails

### ISSUE THREAD

**Issue by mkcms** [joaotavora/eglot#27]
In a buffer with these contents:
`void foo(){}
`
Calling `eglot-format-buffer` when using clangd server results in:
`void foo {}
`
Expected result is:
`void foo() {}
`

This is because `eglot--apply-text-edits` calls `eglot--range-region` which returns wrong results when it's argument is an empty range (empty ranges are valid in LSP). This bug was introduced in 142cc5eb23a8bab1b3cf27bc63a9ede2c4d884a7.

**Comment by joaotavora** [comment]
Nice report, I'll have a look.

**Comment by adonovan** [comment]
The fix for this issue (zero-width ranges) included this code:
```lisp
                       ;; Fallback to `flymake-diag-region' if server
                       ;; botched the range
                       (when (= beg end)
			 (if-let* ((st (plist-get range :start))
				   (diag-region
				    (flymake-diag-region
				     (current-buffer) (1+ (plist-get st :line))
				     (plist-get st :character))))
			     (setq beg (car diag-region) end (cdr diag-region))
			   (eglot--widening
			    (goto-char (point-min))
			    (setq beg
				  (eglot--bol
				   (1+ (plist-get (plist-get range :start) :line))))
			    (setq end
				  (line-end-position
				   (1+ (plist-get (plist-get range :end) :line)))))))
```

This causes Emacs to highlight the character _before_ the indicated range, which is often an irrelevant blank space, instead of the character after, which is the token of interest. (Gopls' nilness analyzers publishes zero-width diagnostics.)

Why is that the appropriate fix, as opposed to something as simple as this?
```lisp
                       (when (= beg end)
                         (setq end (1+ end)))
```

(Aside:  "botched" seems like an unnecessarily pejorative: an empty range is what it is, and sometimes all the information the server has is the start point of a token.)
