### ISSUE TITLE
python-mode's py-help-at-point emits errors continuously

### ISSUE THREAD

**Issue by jukworks** [joaotavora/eglot#299]
I try to set up a python dev env with eglot (ver 20190910.1347), emacs 26.3 (compiled) and pyls. When I open a py file, eglot starts seamlessly.
But whenever I move a cursor (esp. on functions), eldoc-message gives me "wrong number of arguments: (0 . 0), 2". It's OK for me not to get a function signature, but when an error happens, it takes about 0.5 ~ 1 sec. It's annoying.

debug message (with toggle-debug-on-error) tells me
py-help-at-point("%s" "...")
eldoc-message("...")
...

and I checked that py-help-at-point in python-mode (ver 20190912.1653) has zero arguments (defined as (defun py-help-at-point () ...))

What should I do?

**Comment by jukworks** [comment]
after I set eglot-put-doc-in-help-buffer to t, short freezes disappear.

**Comment by nemethf** [comment]
python-mode shipped with emacs-26.3 does not have a function named py-help-at-point.  There's an update in GNU ELPA, but that does not have that function either.  Which python-mode are you using?

**Comment by jukworks** [comment]
I installed python-mode from MELPA, version 20190912.1653.

**Comment by nemethf** [comment]
OK.  So the problem seems to be between eldoc-message and py-help-at-point, neither of which is part of eglot.  However, even in emacs 26.1, eldoc-message calls eldoc-message-function with two arguments.  So, I suspect the bug is in python-mode.   I suggest to open a bug report there.

I'm closing this issue, but feel free to reopen if you disagree.
