### ISSUE TITLE
*_flymake.* files appear in Treemacs

### ISSUE THREAD

**Issue by andreyorst** [joaotavora/eglot#325]
When I'm opening any file that will be managed by eglot a file appears in Treemacs buffer:

![image](https://user-images.githubusercontent.com/19470159/67571490-ba777480-f73c-11e9-9174-592a16ca9b13.png)

Manually refreshing Treemacs with <kbd>g</kbd> removes these entries. I'm not sure if this is flymake bug though, or maybe Treemacs.

**Comment by joaotavora** [comment]
This is a flymake bug.  Well more or less.  It's a bug if the files are not deleted automatically. If they are it's a Treemacs bug. If they aren't it's a Flymake bug.

Regardless, creating the files in the first place is a bad idea from the part of Flymake.  It's a remnant of the old Flymake (before the redesign) that I didn't take out because of backward compatiblity reasons.  We can ask in emacs-devel for this legacy behaviour to be removed.

You can get rid of this legacy behaviour by putting this in your `.emacs`:
```
(remove-hook 'flymake-diagnostic-functions 'flymake-proc-legacy-flymake)
```

**Comment by andreyorst** [comment]
Files are removed, Treemacs seem not to refresh automatically in this case though. It's also an `sshfs` mounted volume, so may be this affects the refreshing.

By removing this hook would I experience some issues while using eglot?

**Comment by joaotavora** [comment]
> By removing this hook would I experience some issues while using eglot?

No, nothing.

**Comment by andreyorst** [comment]
OK, I think this is solve then.
