### ISSUE TITLE
Events buffer constantly grows

### ISSUE THREAD

**Issue by proofit404** [joaotavora/eglot#41]
Thanks for an awesome package!

Looks like there is no cleanup implemented for event buffer yet?

Or am I missing something?

**Comment by joaotavora** [comment]
> Looks like there is no cleanup implemented for event buffer yet?
>
> Or am I missing something?

No you aren't.  If you want to implement truncating the buffer after a given length, it's all yours.  The only thing to note is that that particular bit of functionality is now in Emacs in the jsonrpc.el library (http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/jsonrpc.el).

So one would have to add the feature there first, increase the version number, and GNU ELPA should pick up the new fixed version.

**Comment by joaotavora** [comment]
Hi,

I've pushed a change to jsonrpc.el that allows a configurable scrollback size.  I'm thinking of setting it to 2Megs, which should solve the memory hogging issue and still provide decent debug capabilities by default.  In Javascript, it fills up very quickly because the server blurts out a lot of info.  In other servers it fills more slowly.

Do you think 2 Megs is too much/too little?

**Comment by proofit404** [comment]
I think 2 megabytes is a sophisticated default. Thanks! I think we can mark this issue as resolved.

**Comment by joaotavora** [comment]
> think we can mark this issue as resolved.

Sorry, we can't.  I haven't actually done the work yet. :-)

**Comment by proofit404** [comment]
Yay!
