### ISSUE TITLE
dart_language_server is obsolete. Use analysis_server instead.

### ISSUE THREAD

**Issue by ram535** [joaotavora/eglot#412]
`dart_language_server` is obsolete. It is suggeted to use [analysis_server](https://github.com/dart-lang/sdk/tree/master/pkg/analysis_server). It comes with the Dart SDK.
It can be run like this:
```
dart dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp
```

**Comment by bradyt** [comment]
@ram535 Why did you close this? If you agree it should be open, can you reopen?

**Comment by bradyt** [comment]
@joaotavora Can you reopen this?

**Comment by joaotavora** [comment]
> @joaotavora Can you reopen this?

I can, but, even better, you could propose a pull request that switches to the new server.  If indeed `dart_language_server` is obsolete, and not just some person's opinion.

**Comment by bradyt** [comment]
From: https://github.com/natebosch/dart_language_server

> An obsolete shim on the analysis server following the language server protocol - use the analysis server with `--lsp` instead https://pub.dev/packages/dart_language_server

**Comment by bradyt** [comment]
I had tried a few weeks ago, but ran into issues and hadn't made time to attempt further. Here is a quick example that seems to work in a clean environment.

We can consider this a draft? At least it's here for people to test.

```elisp
(setq eglot-server-programs
      `((dart-mode . ("dart"
                      ,(expand-file-name "snapshots/analysis_server.dart.snapshot"
                                         (file-name-directory
                                          (file-truename
                                           (executable-find "dart"))))
                      "--lsp"))))

```

**Comment by joaotavora** [comment]
Right, this is probably something that people can put in their `.emacs` files.  Do you think it's suitable `dart-mode` entry though?

**Comment by bradyt** [comment]
> Right, this is probably something that people can put in their .emacs files.

I agree. Let's let users (me for example) get a chance to put this through a few rounds. Users may frequently have two installs of Dart, because of Flutter. I'm not sure yet whether or not that can create issues. I'm not a consistent user of LSP, hence why I've been coming around to this issue very slowly.

> Do you think it's suitable dart-mode entry though?

As for if this entry is actually right for eglot.el, ... my opinion should come later, once I've had a chance to test this rudimentary config, then also to see what idioms you have in documentation and examples. Presumably, we shouldn't use a backtick. My elisp skills can be that slow at times.

This is part of why I hoped to leave this open. I don't have the immediate fix. When I first noticed this issue some weeks ago, I hadn't even managed an update like the above, without causing errors, and deferred it for later. I woke up to LSP-related github issues this morning, hence why I suddenly revisited this issue.

But I'd like to continue researching this when I make time for it.

**Comment by zw963** [comment]
this issue is too old.

I create a new issue #861, let us discuss there, if anyone have working config, please share there too, thank you.
