### ISSUE TITLE
Problems changing major modes of eglot-managed buffers

### ISSUE THREAD

**Issue by mkcms** [joaotavora/eglot#44]
Steps to reproduce:

1. Visit a C header (in `c-mode`)
2. `M-x eglot`
3. `M-x c++-mode`
4. Try to kill current buffer
5. Buffer is not killed, error is signaled:

`Debugger entered--Lisp error: (jsonrpc-error "No current JSON-RPC connection" (jsonrpc-error-code . 32603) (jsonrpc-error-message . "No current JSON-RPC connection"))`

This is because `kill-buffer-hook` (which calls `eglot--signal-textDocument/didClose`) is a permanent local variable, which means it isn't cleared after changing major modes.

**Comment by joaotavora** [comment]
This was tricky to fix, but I did spot some other bugs, so thanks very much for the report.  Can you check?

The other bug was quite serious and easy to trigger.  Just kill a managed buffer and then try to `M-x eglot-shutdown`...

**Comment by mkcms** [comment]
It fixes this problem, thanks. Now if I change to c++-mode from c-mode, I get this message (in `emacs -Q`):
`Error in post-command-hook (#[0 "\304\305\303\242\306#\210\307\302!\205\0r\302q\210\310\311\312\301\"\300\")\207" [nil (post-command on-display) #<buffer simulation.h> (#0) remove-hook post-command-hook nil buffer-live-p flymake-start remove post-command] 4]): (wrong-type-argument hash-table-p nil)`

But I think it might be caused by flymake.

**Comment by joaotavora** [comment]
Hmm, very interesting.  Can you post the entire recipe from `emacs -Q`?  What server is this with? `clangd` enough?  Is it always reproducible?

**Comment by mkcms** [comment]
> What exactly is in /tmp/foo.py or is it a brand new file?

It's a new file.

> Do you have to make this very quickly?

No.

> I can't reproduce with your recipe.

Let me know how I can debug it.

**Comment by joaotavora** [comment]
> Let me know how I can debug it.

Well, I have the feeling that indeed the problem is in flymake, particularly in `flymake-start`.

You can start by setting `warning-minimum-log-level` to `:debug` and checking the flymake error log (click Flymake in the mode-line).

You could also `edebug` the function `flymake-start`.  But it could be tricky.  Maybe just `trace-function` it to understand when it is being called.

I have the feeling that a fix in Eglot's side could be disabling flymake before changing major mode, so if that is feasible, I'll preemtively push it and you can test.

No idea why the problem doesn't happen in my side.  What exact version of Emacs are you using?

**Comment by joaotavora** [comment]
NEVERMIND, I've just reproduced it.  My mistake, I was using a previous eglot.el version
