### ISSUE TITLE
Requiring emacs 26.1 is not enough anymore 

### ISSUE THREAD

**Issue by nemethf** [joaotavora/eglot#483]
Eglot now depends on eldoc 1.0.0, which in turn depends on emacs 26.3.  So would it make sense to require emacs 26.3 or instead would it be better to just remove this explicit dependency? 

(I'm mainly on debian stable, which has emacs 26.1, but I'm not complaining.  Well, now I do, but you can ignore it.)

**Comment by joaotavora** [comment]
On Mon, May 18, 2020 at 3:21 PM Felicián Németh <notifications@github.com>
wrote:

> Eglot now depends on eldoc 1.0.0, which in turn depends on emacs 26.3. So
> would it make sense to require emacs 26.3 or instead would it be better to
> just remove this explicit dependency?
>

Or maybe eldoc 1.0.0 works fine on Emacs 26.1. The minor releases don't
change much, so that's likely.

> (I'm mainly on debian stable, which has emacs 26.1, but I'm not
complaining. Well, now I do, but you can ignore it.)

Doesn't emacs 26.1 have a serious security flaw or something?

**Comment by nemethf** [comment]
> Or maybe eldoc 1.0.0 works fine on Emacs 26.1. The minor releases don't change much, so that's likely.

Emacs 26.1 complies eldoc 1.0.0 without any warings or errors.  On the other hand, compiling the elpa xref results in this:
```
In end of data:
xref-1.0.1.el:1451:1:Warning: the following functions are not known to be defined: ring-resize,
    next-error-found, project--process-file-region
```

Looking at the 26.3 release on savannah, it seems project--process-file-region is not present in emacs 26.3 either.

> Doesn't emacs 26.1 have a serious security flaw or something?

I think debian backports bug fixes to older releases.  I'm not sure.

**Comment by nemethf** [comment]
> Emacs 26.1 complies eldoc 1.0.0 without any warings or errors. On the other hand, compiling the elpa xref results in this:  [...]

I made a mistake there, I didn't realized project.el is also in ELPA. Sorry.

At any rate, now I think it would be better to let the dependencies decide which Emacs version Eglot ultimately depends on.

**Comment by joaotavora** [comment]
That's not a bad idea, indeed. But are we sure we're not implicitly
depending on some preloaded stuff that is available only in a specific
emacs?

**Comment by jovlinger-chwy** [comment]
This issue is a year old, yet still plagues us.  The most recent build available on https://emacsformacosx.com/ is 26.2-2.  Is there someway to install a stub eldoc?

**Comment by skangas** [comment]
Given that Emacs 28.1 will soon be released, and we already depend on Emacs 26.1, I don't think that support for Emacs 25 or earlier is very important. If anyone wants to work on that, they are very welcome to send a PR and we will look at it.

I therefore think it's okay to leave things as they are and do nothing here, and I'm closing this bug. If anyone disagrees, please write your rationale and we could reconsider.

PS. I hope that @joaotavora agrees with me here, otherwise he will re-open. ;-)

**Comment by joaotavora** [comment]
Yeah it's fine. Good call. Thanks for all this brooming :-)

**Comment by nemethf** [comment]
This issue was about Emacs 26.1, not Emacs 25 or earlier.  But Debian stable now has Emacs 27.1, so I'm OK with closing this issue.  Thanks.

**Comment by skangas** [comment]
> This issue was about Emacs 26.1, not Emacs 25 or earlier. 

The last posts in this thread discuss dropping the Emacs 26.1 dependency and focusing on just specific version of packages. My conclusion was that we might as well keep the Emacs 26.1 dependency, thereby not support Emacs 25 or earlier.

> But Debian stable now has Emacs 27.1, so I'm OK with closing this issue. Thanks

Thanks for reporting back.
