### ISSUE TITLE
List _all_ diagnostics across multiple files

### ISSUE THREAD

**Issue by garyo** [joaotavora/eglot#504]
I'm in the midst of a big refactoring. It would be great if eglot could show a list of _all_ diagnostics across all the files it's managing. Currently each file has a flymake diagnostics buffer `(flymake-show-diagnostics-buffer)` which is useful but I'd like to see a global version of that like VS Code has.

**Comment by joaotavora** [comment]
ACK, this is a useful feature.  We must synch this with `flymake.el` and `project.el` and some LSP support for the notion of project.

**Comment by garyo** [comment]
Thanks! Quick note, as a stopgap, without any additional project info, you could just list somewhere all the `publishDiagnostics` results returned by the server (or even just the list of files with issues). Right now I'm just searching through the eglot events buffer looking for `publishDiagnostics` results to see which files have problems.

**Comment by joaotavora** [comment]
I prefer a proper solution instead of inventing some half-baked bug-ridden complicated solution in Eglot that I will eventually have to tear down.

**Comment by garyo** [comment]
Haha, absolutely. Thank you!

**Comment by dgutov** [comment]
I wonder: does VS Code show all diagnostics for all files in the project, or only for those files that you opened before, in the current session?

**Comment by joaotavora** [comment]
No idea, and not particularly relevant IMO. I have seen some LSP servers communicate diagnostics diagnostics back to the LSP client for _all_ files that the LSP server somehow knows are managed, though most servers only bother with the files you've sent a `didOpen` for or the one targeted by the most recent change.  There doesn't seem to be a piece of LSP specification about this: probably there should be.

**Comment by joaotavora** [comment]
I'm sorry: what I mean is not relevant is the VS Code behaviour, not the rest of your question.

**Comment by dgutov** [comment]
I'm guessing VS Code's behavior just follows what the servers do, so that's what I was asking about.

The spec seems to have it defined, but the description is vague enough to be interpreted in different ways:

> if a language has a project system (for example C#) diagnostics are not cleared when a file closes. When a project is opened all diagnostics for all files are recomputed (or read from a cache)

So they're probably supposed to send all known diagnostics.

Either way, I'm curious how VS Code deals with this. Perhaps it just shows the latest version of what the server has sent. Because I don't think taking the full list of files and requesting diagnostics for all of them is a practical option.

**Comment by joaotavora** [comment]
For Emacs, I'd just show whatever we have, in a consolidated "Flyamek diagnostics" buffer.  I guess that matches more or less "what the servers do"

> So they're probably supposed to send all known diagnostics.

Where exactly are you reading this?  I don't read this as the typical language of the specification.  But anyway, it's the server's problem, not ours.

**Comment by dgutov** [comment]
> Where exactly are you reading this?

From "diagnostics are not cleared when a file closes". The alternative interpretation would be to read this as a detail internal to the server implementations. But why would the protocol describe such a detail?

> For Emacs, I'd just show whatever we have, in a consolidated "Flyamek diagnostics" buffer. I guess that matches more or less "what the servers do"

Yup.

**Comment by joaotavora** [comment]
> From "diagnostics are not cleared when a file closes". The alternative interpretation would be to read this as a detail internal to the server implementations. But why would the protocol describe such a detail?

Because it's not exactly an IEEE RFC... But you can search in the LSP issues, https://github.com/microsoft/language-server-protocol/issues/, for some issue trying to tacke this, or create a new one.  I think it makes sense to clarify.  I don't have the energy to engage right now, so I would do the simple thing I described above (which depends on how servers behave) and wait for feedback.

**Comment by joaotavora** [comment]
Let's continue in #683
