### ISSUE TITLE
eval: Symbol’s value as variable is void: tab-prefix-map

### ISSUE THREAD

**Issue by CDitzel** [joaotavora/eglot#530]
Using Emacs 26.3 I get 

eval: Symbol’s value as variable is void: tab-prefix-map

when using 

(use-package eglot)

why is that? I cannot find anything related in the internet

**Comment by joaotavora** [comment]
Carsten Ditzel <notifications@github.com> writes:

> Using Emacs 26.3 I get
>
> eval: Symbol’s value as variable is void: tab-prefix-map
>
> when using
>
> (use-package eglot)
>
> why is that? I cannot find anything related in the internet

I don't know either.  Emacs has many configuration options and external
packagesthat might be interfering.  For me to help you, we need to
systematically rule out these interferences. Please try to follow the
bug-reporting instructions in the README.  Thanks.

João

**Comment by muffinmad** [comment]
I think it comes from `project.el`. See [this commit](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=b63c5a7efc89c23230f53a346e29e72a9b4faafc).

Invoking `package-initialize` with the latest version of `project.el` from ELPA installed in Emacs 26.3 will lead to this error:

```
Debugger entered--Lisp error: (void-variable tab-prefix-map)
  (define-key tab-prefix-map "p" (function project-other-tab-command))
  eval-buffer(#<buffer  *load*> nil "/tmp/tmp-elpa26/project-0.5.1/project-autoloads.el" nil t)  ; Reading at buffer position 2596
  load-with-code-conversion("/tmp/tmp-elpa26/project-0.5.1/project-autoloads.el" "/tmp/tmp-elpa26/project-0.5.1/project-autoloads.el" nil t)
  load("/tmp/tmp-elpa26/project-0.5.1/project-autoloads" nil t)
  package--activate-autoloads-and-load-path(#s(package-desc :name project :version (0 5 1) :summary "Operations on the current project" :reqs ((emacs (26 3)) (xref (1 0 2))) :kind nil :archive nil :dir "/tmp/tmp-elpa26/project-0.5.1" :extras ((:url . "http://elpa.gnu.org/packages/project.html")) :signed t))
  package--load-files-for-activation(#s(package-desc :name project :version (0 5 1) :summary "Operations on the current project" :reqs ((emacs (26 3)) (xref (1 0 2))) :kind nil :archive nil :dir "/tmp/tmp-elpa26/project-0.5.1" :extras ((:url . "http://elpa.gnu.org/packages/project.html")) :signed t) nil)
  package-activate-1(#s(package-desc :name project :version (0 5 1) :summary "Operations on the current project" :reqs ((emacs (26 3)) (xref (1 0 2))) :kind nil :archive nil :dir "/tmp/tmp-elpa26/project-0.5.1" :extras ((:url . "http://elpa.gnu.org/packages/project.html")) :signed t) nil deps)
  package-activate(project)
  package-initialize()
```

Because `tab-bar-mode` is added in Emacs 27.

**Comment by CDitzel** [comment]
but I am using 26.3 not 27 oO

**Comment by muffinmad** [comment]
> but I am using 26.3 not 27 oO

With which version of `project.el`?

**Comment by joaotavora** [comment]
Thank you Andrii: this has to be reported as a bug in the Emacs's bug
tracker. Project.el must be kept compatible with Emacs 26.3, as announced
in the file's header. If you can, make the bug report. Please put me,
project's maintainer Dmitry Gutov and the commit's author, Sean Whitton in
the X-Debbugs-CC: field of the bug report, or reply with CC to them to the
bug acknowledgment email.

The fix is likely to make the new section of code be conditional on the new
tab-bar feature.

João

**Comment by muffinmad** [comment]
> Project.el must be kept compatible with Emacs 26.3, as announced in the file's header. If you can, make the bug report.

[Bug report](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=43164) for `project.el` issue.

**Comment by joaotavora** [comment]
I fixed this in Emacs's `project.el`, should be available in GNU Elpa now. Closing this.  @CDitzel, if you find the problem persists, let us know here.
