### ISSUE TITLE
vls does not report any diagnostics on .vue files

### ISSUE THREAD

**Issue by vikigenius** [joaotavora/eglot#548]
I am not sure how to debug this. vls seems to be starting up fine, but when I look at the jsonrpc there doesn't seem to be any diagnostics published.

the same code when tested with `vti diagnostics` on the cli does show errors in my code. Any help would be appreciated.

**Comment by muffinmad** [comment]
I'm not familiar with vls, but let's try to debug this.

Is [this code](https://github.com/vuejs/vetur/blob/5cc549a5642e28af941343f1365cc0954233a16d/server/src/services/vls.ts#L542) is responsible for diagnostic publishing?

If so, which mode do you use to edit `.vue` files?

In Eglot events buffer (`M-x eglot-events-buffer`), check `languageId` of your document in the `textDocument/didOpen` method. If it differ from `vue`, then no diagnostic will be gathered because of `if (doc.languageId === 'vue')`.

**Comment by vikigenius** [comment]
@muffinmad Thanks I have managed to solve part of my issue:

Originally I was using a custom-derived-mode of web-mode that I named "vk-vue" so that it may not conflict with some existing vue-mode. 

But once I fixed that and changed it to vue-mode, I can see diagnostics being published in the events buffer but it doesn't actually show up. I think that is mainly because I am using doom-emacs and it is somehow using flycheck instead of flymake based on these two files:

https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/lsp/autoload/flycheck-eglot.el
https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/lsp/%2Beglot.el

Thanks a lot for helping me make some headway on this issue.

**Comment by muffinmad** [comment]
> Originally I was using a custom-derived-mode of web-mode that I named "vk-vue" so that it may not conflict with some existing vue-mode.

You may be interested in this PR: https://github.com/joaotavora/eglot/pull/542

> https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/lsp/autoload/flycheck-eglot.el

So they "translate" flymake errors to flycheck errors? Omg :)
It's better to ask help for this in their issue tracker.

If you think something must be done here on Eglot side, please retitle the issue. Otherwise close this issue. Thanks!

**Comment by purcell** [comment]
> So they "translate" flymake errors to flycheck errors? Omg :)

LOL, probably my bad: that looks like it's based on some code I unwisely shared in a gist. 😂
