### ISSUE TITLE
index also system include files in c++?

### ISSUE THREAD

**Issue by xwl** [joaotavora/eglot#551]
When following the types defined in some system include files, for example, inside the vector file, one can't look up definitions of objects defined (e.g., __vector_base) there, the file seems simply not indexed.

This is one feature that i missed a lot from rtags (where rtags supports it quite well)

**Expected behavior**

Able to find definitions inside system include files

**Steps to reproduce**

 1. open your project, follow definition of std::vector
 2. inside the file, try to follow definition of its base class "__vector_base"

You will get, file not indexed error.

I reported the issue first to ccls, the author told it is a client issue, and that lsp-mode actually supports this:  https://github.com/MaskRay/ccls/issues/707

**Comment by joaotavora** [comment]
This issue is almost certainly similar to an existing one that popped up near the beginning of the Eglot project, but we will use this new one to track this issue.

The problem is that, by definition, a system include file, is outside your project, physically.  Eglot may manage many concurrent projects and there's currently no way of  telling, or guessing,  which one of those projects you want to ber associated with the given system include file.  Depending on the particular project you are working on (say, they, use different compilers or compiler flags), I guess step `2` as you described above could take you to a different location.

On the other hand, it is plain to see that this is counter-intuitive: someone navigate away from an Eglot managed buffer into a non-managed one and suddently all of the client stops working.  So we should probably come up with a way to let at least part of the Eglot client to remain active in these buffers, even if it doesn't make sense to fully manage them (for example, it doesn't make sense to track changes, but it does make sense to provide cross-referencing support).

**Comment by stephe-ada-guru** [comment]
João Távora <notifications@github.com> writes:

> This issue is almost certainly similar to an existing one that popped
> up near the beginning of the Eglot project, but we will use this new
> one to track this issue.
>
> The problem is that, by definition, a system include file, is outside
> your project, physically. Eglot may manage many concurrent projects
> and there's currently no way of telling, or guessing, which one of
> those projects you want to ber associated with the given system
> include file. Depending on the particular project you are working on
> (say, they, use different compilers or compiler flags), I guess step
> `2` as you described above could take you to a different location.
>
> On the other hand, it is plain to see that this is counter-intuitive:
> someone navigate away from an Eglot managed buffer into a non-managed
> one and suddently all of the client stops working. So we should
> probably come up with a way to let at least part of the Eglot client
> to remain active in these buffers, even if it doesn't make sense to
> fully manage them (for example, it doesn't make sense to track
> changes, but it does make sense to provide cross-referencing support).

I solve this problem by having a single global project, and a
project-find-functions that just returns that project, with no searching
for anything. That's provided by the ELPA package "wisi", which also
provides various methods for creating such projects, and selecting the
currently active one.

This is more of a project.el issue than an eglot issue.

-- 
-- Stephe

**Comment by xwl** [comment]
> (for example, it doesn't make sense to track changes, but it does make sense to provide cross-referencing support).

This will probably cover the most (if not all) use cases already. 

Maybe we associate the system files to all projects that use them, depending on how the user ends up in that file, we dynamically switch the associated projects? (That would mean multiple copies of the indexing results for the same file may be needed)  If the user just comes back to the file buffer with switch-to-buffer, instead of xref-find-definitions, then we don't change the associated project.

@stephe-ada-guru that is still a workaround. It seems I can also just force eglot--guess-contact to return my project (instead of the 'transient' values, as it would do now), to make it index system files.

**Comment by joaotavora** [comment]
Hello @stephe-ada-guru, thanks for dropping by:

> I solve this problem by having a single global project, and a
> project-find-functions that just returns that project, with no searching

This confuses me.  Do you use one single global project for every,  err, project?  Isn't this contradictory with the very idea of projects which are a way to segregate your files into logical units? 

> @stephe-ada-guru that is still a workaround. It seems I can also just force eglot--guess-contact to return my project (instead of > the 'transient' values, as it would do now), to make it index system files.

@xwl, I also don't understand how that helps. 

I do think Stephen is right in claiming this can be seen as a `project.el` issue, or at least I think this has to be solved in close coordination with that library.  It is in my opinion conceivable that Eglot uses `project.el` to express that those system includes belong to a given project. The problem is that, it would seem, they belong to *many* projects, at least potentially.  But maybe we can assume that they belong to a single project _at any given time_.

Thus, I can imagine some way that we have a project search function (i.e. a member of `project-find-functions`) return a given "current" or "recent" Eglot project, as per that variable's protocol.  If this happened, I think that Eglot would probably pick up on it and things would work as desired.  To clarify a bit in pseudo-code, this would go into one's `.emacs`:
```lisp
(defun joaot-project-find-current-eglot-project (dir)
   (and (system-includes-dir-p dir)
        (current-eglot-project))

(add-hook 'project-find-functions `joaot-project-find-current-eglot-project)
```

Note that:

* I have no idea if this would work;
*  this means that this function would return different values not only based on its arguments, but also based on a secondary global state (given by `current-eglot-project`, a function that is yet to be written and that would somehow rely on a global variable).  
* this would return a directory *outside* the `project-root` of the `current-eglot-project`. 

I have no idea if any of the last two characteristics break some fundamental `project.el` assumptions and would be problematic for the future. Something to query the maintainer of project.el about, I guess.

**Comment by joaotavora** [comment]
> provides various methods for creating such projects, and selecting the
currently active one.

@stephe-ada-guru I think I understand your strategy right now.  You seem to have one global active project _at any given time_.  In that case, my proposed solution is similar to yours, but it's not as restrictive.  It's very similar in its need to "select the currently active project".

**Comment by stephe-ada-guru** [comment]
João Távora <notifications@github.com> writes:

> Hello @stephe-ada-guru, thanks for dropping by:
>
>> I solve this problem by having a single global project, and a
>> project-find-functions that just returns that project, with no searching
>
> This confuses me. Do you use one single global project for every, err,
> project?

Each project defines a set of files, as you expect.

project-find-functions then determines which one of those projects is
returned by (project-current) - that is, which project is current.
Typically a project-find-function searches for a root directory,
starting at the current buffer's file.

In my case, no search is performed; the current project is set
explicitly by the user, so it is independent of the current buffer.

This explicitly avoids the notion of "project root", which is
meaningless or wrong when you consider system files.

This has some downsides; if you are in a buffer whose file is _not_ in
fact a member of any project, (project-current) still says it is. So
far, that doesn't bother me; it typically happens in files where
I'm not invoking project functions anyway.

You can still have buffer-dependent projects by defining a buffer-local
value for project-find-functions; I do that for elisp files.

> I do think Stephen is right in claiming this can be seen as a
> `project.el` issue, or at least I think this has to be solved in close
> coordination with that library. It is in my opinion conceivable that
> Eglot uses `project.el` to express that those system includes belong to
> a given project. The problem is that, it would seem, they belong to
> *many* projects, at least potentially. But maybe we can assume that they
> belong to a single project _at any given time_.

Backing up a step; the issue is that some files that the user expects to
be included by the LSP server when looking for cross-references are not
in fact included. I believe the LSP protocol has no notion of "project"
(but see below) - it relies on the client to tell it what files to
include. On the Emacs side, we have (project-files (project-current));
it would make some sense to simply send that list to the server when any
new project is opened.

Because that list can be a very large, we tend to do this lazily, and
only notify the server about files when they are opened in Emacs. Then we
should use (member file (project-files (project-current))) to check if a
file is in a project.

This assumes project-files includes system files, which it
should, but I would bet a lot of projects are broken here. That is
a project issue, not an eglot issue, but it's not very friendly to just
say "your project implementation is broken", when people may not have
control over the project implementation.

On the other hand, it appears that some (most?) LSP servers do have a
notion of "project", that matches the compiler/interpreter for the
language the server supports. In that case, the Emacs language mode
should provide an Emacs project that matches the server project. For
example, the Ada language server uses *.gpr files to define a compiler
project, and Emacs ada-mode uses exactly the same files to define the
Emacs project.

> Thus, I can imagine some way that we have a project search function
> (i.e. a member of `project-find-functions`) return a given "current"
> or "recent" Eglot project, as per that variable's protocol. If this
> happened, I think that Eglot would probably pick up on it and things
> would work as desired. To clarify a bit in pseudo-code, this would go
> into one's `.emacs`: ```lisp (defun
> joaot-project-find-current-eglot-project (dir) (and
> (system-includes-dir-p dir) (current-eglot-project))
>
> (add-hook 'project-find-functions `joaot-project-find-current-eglot-project)
> ```
>
> Note that:
>
> * I have no idea if this would work;

It looks like a reasonable approach, as a workaround for broken project
implementations.

>  * this means that this function would return different values not
> only based on its arguments, but also based on a secondary global
> state (given by `current-eglot-project`, a function that is yet to be
> written and that would somehow rely on a global variable).

This could just remember the last project returned; ie wrap
(project-current) with some advice

> * this would return a directory *outside* the `project-root` of the
> `current-eglot-project`.

Yes; I've always said 'project-root' is ill-defined (for example; what
is the "root" of elisp files?). That's why it used to be plural, but
that didn't work very well either. project-files is much better.

> I have no idea if any of the last two characteristics break some
> fundamental `project.el` assumptions and would be problematic for the
> future. Something to query the maintainer of project.el about, I
> guess.

I think it's fine.

--
-- Stephe

**Comment by xwl** [comment]
I think the usual usecase is that, the user will follow some system files from other already opened project files, by using commands like xref-find-definitions. Hence, when invoking such commands, maybe we can simply save the current project before opening the system file buffer, and apply the saved project to the new buffer, then we won't need a global var.

Of course, if the user opens the system file independently by simply find-file,  it won't be mapped to any project. This seems also reasonable.

If user wants to map the same system file to a different project2, he could first close the system file buffer, and visit it again from project2. (Or we can eval again the eglot-ensure when we discovered it was mapped to project1 before? )

**Comment by nemethf** [comment]
Since this discussion dried out, Eglot gained `eglot-extend-to-xref` and it now also supports multiple workspace-folders via `project-external-roots`.  Do these recent changes help here anything?
