### ISSUE TITLE
Order of eldoc-documentation-functions arguably wrong

### ISSUE THREAD

**Issue by jakecoble** [joaotavora/eglot#648]
eldoc considers functions earlier in `eldoc-documentation-functions` to be more important. Since eglot adds its documentation functions to `eldoc-documentation-functions` _before_ enabling flymake-mode, those functions appear earlier in the list and are therefore considered more important.

However, flymake errors are probably more important than documentation functions. Should these functions be reordered?

**Comment by joaotavora** [comment]
> Should these functions be reordered?

Maybe, but I think I tried that and there was something odd in some mode, like sitting on top of an "incompatible arglist" error that you don't know how to fix because the hint is in the arglist hint that you can't see.  So I specifically put in this order.

But you can tweak `eldoc-documentation-strategy`...

**Comment by joaotavora** [comment]
Or maybe Eglot could offer a better default for this variable.

**Comment by jakecoble** [comment]
Yeah, currently I'm using `eldoc-documentation-compose` to see everything, which works well enough.

**Comment by mohkale** [comment]
Yeah. Honestly this was kind of driving me insane. I goto an error and the only message I get is information about the function call or method signature. I then run `flymake-show-diagnostics-buffer` but it doesn't automatically go-to the nearest error I'm at or have something like `flycheck-follow-mode` so I have to manually associate the current line with the diagnostics buffer to find out what's wrong.

I ended up writing this to toggle the ordering of flymake and eglot in the eldoc documentation functions, but I still thing it would be sensible to change the default.

```lisp
(defun eglot-eldoc-toggle-order+ ()
    "Toggle the precedence of flymake notifications in eldoc."
    (interactive)
    (unless (bound-and-true-p eglot--managed-mode)
      (user-error "Must be called from an `eglot' managed buffer"))
    (let* ((pos (cl-position #'flymake-eldoc-function eldoc-documentation-functions)))
      (setq eldoc-documentation-functions
            (if (eq pos 0)
                (append (cdr eldoc-documentation-functions) (list #'flymake-eldoc-function))
              (append (list #'flymake-eldoc-function)
                      (if (zerop pos)
                          (cdr eldoc-documentation-functions)
                        (let ((last (nthcdr (1- pos) eldoc-documentation-functions)))
                          (setcdr last (cddr last))
                          eldoc-documentation-functions)))))
      (message "Message priority: %s"
               (if (eq pos 0)
                   (propertize "Documentation" 'face 'compilation-info)
                 (propertize "Errors" 'face 'compilation-error)))))
```

**Comment by joaotavora** [comment]
Did you read the part (https://github.com/joaotavora/eglot/issues/648#issuecomment-804205658) where I explain about how I have experimented with changing this default and seen it behave in undesirable ways? Also see this suggestion (https://github.com/joaotavora/eglot/issues/648#issuecomment-804208154).

**Comment by joaotavora** [comment]
> (if (eq pos 0)
 >              (append (cdr eldoc-documentation-functions) (list #'flymake-eldoc-function))

You should look into the `sort` or `cl-sort` functions to simplify your code.

**Comment by mohkale** [comment]
@joaotavora 

Much appreciated. Thank you.

**Comment by joaotavora** [comment]
Closing.  If I find the time, I'm going to propose in Emacs that `eldoc-documentation-compose` becomes the default.  Or maybe Eglot should make it the default (PRs welcome for that). It has the potential to show many lines in the echo area, but it still respects `eldoc-echo-area-multiline-p` so there's a way to escape it.

**Comment by lionel-** [comment]
eldoc-compose is a good stopgap but it is rather suboptimal. In my case it often produces too much distracting information. I agree that ideally flycheck/make errors would have precedence over function doc.

**Comment by lionel-** [comment]
Good point. However if I see a diagnostics that doesn't give me sufficient information about the signature I'll just jump to the definition to inspect the signature then jump back to the error point. By contrast, if I only see the signature doc as is the default currently, I have no idea what's wrong. Changing the default to aggregate eldoc information would work, but does not seem as user friendly.

**Comment by joaotavora** [comment]
As always, in Emacs, everyone has a workflow, the nice thing about Emacs is that you can configure things.

I for one, find that very often just the visual underlining/fontification cue on the function call is enough to tell me the parameters order/type/number is wrong.  So the fact that signature info takes priority is important to me.  If I do need to read the error message, I use `flymake-goto-prev-error` and `flymake-goto-next-error` in quick succession, which I have bound to `M-p` and `M-n` respectively in my personal configuration.

You like to work differently, so I would suggest you arrange for `eldoc-documentation-fucntions`, `eldoc-documentation-strategy`, etc to be setup the way you like them.  Then share that snippet of configuration here for other to benefit from.

Arguing for a new default is perfectly legitimate, but then it's the same never-ending discussion/problem in Emacs: you change the default you break someone's config.  I wouldn't mind changing _my_ config, but I don't know if others would also don't mind, especially given they would be caught off guard. This problem is much larger than Eglot and needs a solution (styles, profiles, themes, etc).  There's been a lot of talk and not a lot of action in that front, last I checked.

**Comment by lionel-** [comment]
I agree that this discussion is not about workflows but about defaults. And I agree with OP that the current default is broken, at least for our use cases.

> I for one, find that very often just the visual underlining/fontification cue on the function call is enough to tell me the parameters order/type/number is wrong.

hmm... But how? Is it maybe because you're not working with languages with complex types, or with complex diagnostics? There could be so many different things that are wrong. Just knowing the function signature instead of the diagnostic doesn't help much. And the signature is always a jump-to-def away, whereas the diagnostic buffer is more cumbersome to use as argued by someone else above.

In any case, this is just my input to this discussion. Since we have workarounds I think it's fine not to take action now if you're not convinced or prefer to wait for more inputs.

**Comment by joaotavora** [comment]
> hmm... But how? Is it maybe because you're not working with languages with complex types, or with  complex diagnostics? 

I'm currently working with C++and C#.  The former has a rather complex type system and rather complex diagnostics. Did you miss the "very often"?  It's not the same as "always".   In the infrequent number of cases where I need to refresh my memory of what the error message is, I'll use M-p and M-n, as I previously described.  Have you experimented with that suggestion before expressing incredulity as to how it may work?

> convinced or prefer to wait for more inputs.

I'm waiting for you to share as a Elisp snippet and/or as a diff to eglot.el what you would like the ideal defaults to be.  

Here's my Flymake configuration that enables the aforementioned described workflow:
```
(eval-after-load 'flymake
  `(progn
     (setq flymake-start-syntax-check-on-newline nil)
     (remove-hook 'flymake-diagnostic-functions 'flymake-proc-legacy-flymake)
     (define-key flymake-mode-map (kbd "M-n") 'flymake-goto-next-error)
     (define-key flymake-mode-map (kbd "M-p") 'flymake-goto-prev-error)
     (when (boundp 'flymake-mode-line-format)
       (delete 'flymake-mode-line-title flymake-mode-line-format))))
```

I don't have any eglot configuration, except for this irrelevant bit:
```
(global-set-key [f4] 'eglot-rename)
```

**Comment by lionel-** [comment]
And here we are, having an unpleasant discussion again, as is often the case in the Emacs community. I did not mean to slight you or your workflow.

**Comment by joaotavora** [comment]
I know you didn't, but I asked you a straight question and made a straightforward request. Did you try that alternative workflow? Am I willing to try your workflow, so long as you post the configuration that you would like Eglot to adopt.  IMO that's the thing that advances discussions, not opinion or conjecture about what language other people use.  Eglot and Emacs is a place for very many of those, and that's a good thing.

So post your preferred configuration: I'm not ruling out a defaults change, but I have to be able to at least evaluate the thing you want to change in the concrete.

**Comment by lionel-** [comment]
I use `flymake-goto-next-error` as well but I hadn't noticed that it shows the message in the echo area until you mentioned it. I agree that it's helpful. Though maybe not very discoverable?

The default setting I'm suggesting is:

```elisp
(setq eldoc-documentation-functions '(flymake-eldoc-function
                                      eglot-signature-eldoc-function
                                      eglot-hover-eldoc-function))
```

I find that it's more helpful for both the default eldoc behaviour and with the compose behaviour.

- With the compose behaviour, displaying the error first and then the contextual doc is the more natural order, if you consider you'd like to know the error first.

- With the default behaviour, the error is the information that is most generally relevant. It's often the case that the error is not related to the function at point, and then the signature does not help. E.g. if you try to pass a `foo.bar` to some function `quux` but `foo` does not contain any `bar`. Then knowing the signature of `quux is not helpful.

**Comment by joaotavora** [comment]
Lionel, please show an actual fully functional snippet that I can try, or a diff to to `eglot.el`. I will then evaluate it with `emacs -Q -l eglot.el -l your-snippet.el` in some projects I have lying around

Make sure you specify your preference for `eldoc-documentation-strategy` as well.
Make sure you specify your preference for `eldoc-echo-area-use-multiline-p` as well.

 That snippet, as it is, won't fly. It's almost certainly not the snippet you use, unless you add something to `eglot-stay-out-of`.

I'll consider your opinions and theoretical justifications, but I don't place nearly as much value in those as I do in the actual code that produces a certain observable behaviors, because that's what users will see.
