### ISSUE TITLE
Find definition won't work for external dependencies in Clojure

### ISSUE THREAD

**Issue by Andre0991** [joaotavora/eglot#661]
Hi. I'm experimenting with using `eglot` with Clojure.

I've had no issues so far except that `xref-find-definitions` won't work for external dependencies.
When I use it on some symbol that refers to an external lib, Emacs asks me if I want to create the directory:

```
Directory `/Users/andreperictavares/dev/peric/clj-new/src/clj_new/file:/Users/andreperictavares/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/java/' does not exist! Create it? (y or n) y
```

The expected behaviour would be to open a buffer with the contents of the file in the jar (and manage it in the same project? Not sure).

Here's the an eglot log sample for this issue:

```
[client-request] (id:7) Sun Apr  4 21:44:24 2021:
(:jsonrpc "2.0" :id 7 :method "textDocument/definition" :params
          (:textDocument
           (:uri "file:///Users/andreperictavares/dev/nu/luna/src/luna/logic/error.clj")
           :position
           (:line 4 :character 23)))
[server-reply] (id:7) Sun Apr  4 21:44:25 2021:
(:jsonrpc "2.0" :id 7 :result
          (:uri "jar:file:////Users/andreperictavares/.m2/repository/prismatic/schema/1.1.9/schema-1.1.9.jar!/schema/core.clj" :range
                (:start
                 (:line 0 :character 4)
                 :end
                 (:line 0 :character 15))))
```

## Steps to reproduce
0. [Download](https://clojure.org/guides/getting_started#_clojure_installer_and_cli_tools) the `clojure` binary

1. Download the native clojure-lsp binary in https://github.com/clojure-lsp/clojure-lsp/releases

2. Configure `eglot` to use it
```
(add-to-list 'eglot-server-programs '(clojure-mode . ("clojure-lsp")))
```

3. Clone `clj-new` and install its dependencies.
```
git clone https://github.com/seancorfield/clj-new.git
clj
```

4. Open the project in `Emacs`, go to `clj-new/src/clj/generate/def.clj` and use `xref-find-definitions` on some external lib like `clojure.java.io` ([line 5](https://github.com/seancorfield/clj-new/blob/a14ba8256d9a0e1d659691be211007ea6eb102b2/src/clj/generate/def.clj#L5) in this file).

Note: I'm using Doom Emacs. I think this does not affect anything in regards to this behaviour. Unfortunately, I don't have a clean Emacs for confirming this easily right now. If you suspect this is Doom specific, I can setup a barebones Emacs in a few days.

**Comment by joaotavora** [comment]
> The expected behaviour would be to open a buffer with the contents of the file in the jar (and manage it in the same project? Not sure).

Yeah, this isn't supported. Could it be?  Maybe yes.  But I'm unsure if it should be in the context of Eglot or simply Xref and Project, which are two packages that Eglot depends on. I lean towards Xref and Project.  We can the maintainer of both those projects here, @dgutov, and allow him to give his opinion, or you can open a bug in Emacs' bug tracker, by sending mail to `bug-gnu-emacs@gnu.org` or using `M-x report-emacs-bug`.

Once the Xref + jar opening is sorted (supposing it is doable) we can think about whether that file should be associated with the same project.  Indeed, as you suspect, the situation isn't linear because the file could be also found by `M-.` in some other eglot project.  I think I've done something practical to that effect recently, but I can't remember how.  Perhaps I didn't push it to master :thinking: .  It had something to do with `project-external-roots` which seems like a good concept to apply here.

**Comment by dgutov** [comment]
I don't think it's really Xref or Project's responsibility, but here are some suggestions.

* Emacs can open files inside `.jar` files and other archives. But for some reason `file-name-handler-alist` is only set up to open the archive files themselves differently, but without translation for file names inside. Someone could look into fixing that. Eglot could translate file names returned by the language server into the expected format.
* Or Eglot could simply provide specialized `xref-location` classes, where the `xref-location-marker` location opens a file inside an archive, if needed. This should certainly be doable, whereas the jury is out on #1 (could be some pitfalls, as indicated by nobody having done this yet).
* Yet another twist on the last option: follow in `lsp-mode`'s example and introduce the notion of `url-handlers`: https://github.com/emacs-lsp/lsp-mode/blob/63b594930f99aa1a81dce5118c28f5fdd838fc29/clients/lsp-clojure.el#L285 (customized per-client). In Clojure's case, the language server provides a method `clojure/dependencyContents`, to fetch the dependency's contents. Downside: you probably can't edit the file this way (not sure if you often want to). Upside: it's generalizable to other language servers and other resources. `jdtls` has a similar action called `java/classFileContents`; not sure if there are others yet.

Approach #2 could be conceivably added to xref.el itself. Approach #3 (which I personally like) doesn't have that option.

Regarding how to track which dependencies belong where, I don't have much better to suggest than some ad-hoc options (perhaps track the list of files/buffers opened this way, associated with a project, or perhaps track lists of directories, if LSP servers report "library paths"). If you go the "virtual buffer" route (#3), it could simply have `default-directory` value belonging to the project.

As you are both the provider and the consumer of the project information in this case, I'm not sure if following the project.el framework holds much value to you. E.g., you could set `project-vc-external-roots-function` in Eglot-managed buffers, but would users expect their project-related command to change behavior because they simply started using Eglot? I'm not sure. Using the existing `project-find-functions` can be handy to avoid choosing such logic by yourself (if the LSP protocol doesn't give any advice on that), but you have no requirement to limit yourself to project.el's structures otherwise.

Here's what I've done in another tool (not LSP-related): for each open project, there is a corresponding connection buffer. That buffer has a buffer-local variable set to the "library path" for that project. Then I do a linear search across such buffers whenever the current file is seemingly not attached to any project directly.

**Comment by joaotavora** [comment]
I said Xref becasue this is a general cross-referencing problem. It could conceivably exist without LSP, which is Eglot's main business, and be useful in other situations. 

> Eglot could translate file names returned by the language server into the expected format.

Translate LSP formats into Emacs formats is indeed Eglot's business. But where can I get hold of this "expected format"?

If no expected format exists, we should make one. That's number 2 and it should live in Xref (or `xref-backends.el` or `xref-utils.el` distributed separately)

> In Clojure's case, the language server provides a method clojure/dependencyContents

This is the curious absurdist view of  LSP as  language-agnostic-but-not-really.  These extensions  belongs in `clojure-mode-.el`, obviously.  But if emacs-lsp has some generic `url-handlers` trick to open files inside jars then maybe it could contribute them to Emacs so that more packages can benefit.

> Regarding how to track which dependencies belong where [...] Here's what I've done in another tool (not LSP-related): 

If the same problem is being solved inside and outside the scope of LSP, this again hints at the need of a shared library.

But first I'd solve the file-finding problem.

**Comment by dgutov** [comment]
> I said Xref becasue this is a general cross-referencing problem. It could conceivably exist without LSP, which is Eglot's main business, and be useful in other situations.

It explicitly encourages extensibility to allow for special cases. I'm not sure how "core" finding files inside archives is to its purpose is, but if it's implemented sufficiently general, it could be added.

If you go this route, do consider option #1 first. It should take ~ the same amount of code, but then you'd be able to address files inside archives anywhere, not just using Xref.

I also wonder which of the approaches would work better with Tramp. Like, if the LS is on a remote host, and we add an addressing scheme for files inside archive files, would Tramp have to add special handling for files inside archives on remote hosts?

> This is the curious absurdist view of LSP as language-agnostic-but-not-really.

The view of current reality, *shrug*.

> These extensions belongs in clojure-mode-.el, obviously. But if emacs-lsp has some generic url-handlers trick to open files inside jars then maybe it could contribute them to Emacs so that more packages can benefit.

These handlers are per-server, not per-language (but good luck convincing `clojure-mode` maintainers anyway). lsp-clojure and lsp-java also have different handlers, even though the end behavior is very similar, because different servers use different urls and commands.

> If the same problem is being solved inside and outside the scope of LSP, this again hints at the need of a shared library.

The implementation is trivial, the real difficulty is choosing which data to use, and where to get it from.

**Comment by joaotavora** [comment]
> If you go this route, do consider option #1 first. It should take ~ the same amount of code, but then you'd be able to address files inside archives anywhere, not just using Xref.

That sounds fine.  But you said there's a format that Eglot should translate to.  Where is that format?  Or should I invent it inside Emacs and distribute a package from it?   Didn't you say there is code to find files inside jars?  

> The view of current reality, shrug.

My concrete reality as someone who actually _uses LSP_ is using it without any such trash.

> (but good luck convincing clojure-mode maintainers anywa

I don't use clojure, so I'm not going to be doing any convincing.  Clearly doesn't belong in Eglot.  You said there's a clojure server with some third-party fancy extensions, maybe clojure-mode maintainers or someone else wants to leverage that using Eglot as a library

> The implementation is trivial, the real difficulty is choosing which data to use, and where to get it from.

I wasn't referring to the implementation, just pointing out that the problem seemingly reaches out of LSP.  I don't fully understand the problem and its quirks yet, though.  My naive understanding of the statement is "how to have a file somehow referenced by two projects, and what advantages and limitations does that bring?"

**Comment by dgutov** [comment]
> Where is that format? Or should I invent it inside Emacs and distribute a package from it?

Invent, yes. Create a file name handler and distribute it from somewhere. But first I would check why it's still not done yet: after all, archive files themselves already have file name handlers.

>  Didn't you say there is code to find files inside jars?

It certainly exists, since you can visit a `.jar` file and even RET into any of its contents. But I haven't looked in detail into where this code resides.

> You said there's a clojure server with some third-party fancy extensions, maybe clojure-mode maintainers or someone else wants to leverage that using Eglot as a library

As long as there is a good extensibility story, I suppose interested parties could create an `eglot-clojure` package. Or indeed incorporate that into a major mode, whatever.

But it will require infrastructure, such as the use said url handlers in the eglot-specific location type's `xref-location-marker` implementations. Or, if you go the file-name-handlers route, in the translation of uris returned by the server to the file names in the format understood by the file name handler.

> I wasn't referring to the implementation, just pointing out that the problem seemingly reaches out of LSP. I don't fully understand the problem and its quirks yet, though.

It's the kind of problem that doesn't easily lend itself into being extracted into a library. `project.el` could end up solving it for its goals one day, and then documenting it, and the only part you'd really be able to reuse is the documentation, I think.

> My naive understanding of the statement is "how to have a file somehow referenced by two projects, and what advantages and limitations does that bring?"

My solution is essentially a hack (just use the most recently used project that has this file in the "externals" set), with the upside of having most features seamlessly working, and the downside of sometimes not guessing the user's intent correctly (using the "wrong" project is more problematic for some commands than others, e.g. it's fine for "find definition" but not for "find references").

**Comment by joaotavora** [comment]
> But first I would check why it's still not done yet: after all, archive files themselves already have file name handlers.

How to check that?  If you have any suspicions, please share, else I think it's easier just to try it. 

> Or, if you go the file-name-handlers route, in the translation of uris returned by the server to the file names in the format understood by the file name handler.

In this case, since there is no format and I'm supposed to invent one, I might as well just use the same format as the clojure LSP server is using here, if it's minimally useful.  So no translation necessary.  Else, if LSP comes up with an official format that's not gratutiously different,  translation is Eglot's job.

**Comment by dgutov** [comment]
> How to check that? If you have any suspicions, please share, else I think it's easier just to try it.

Try the code, search its history, `Cx v g`, ask the people who touched it in the past. Michael, probably.

> In this case, since there is no format and I'm supposed to invent one, I might as well just use the same format as the clojure LSP server is using here, if it's minimally useful.

IIUC there are some considerations to use for choosing particular addressing scheme. Michael could advise on that as well.

> Else, if LSP comes up with an official format that's not gratutiously different, translation is Eglot's job.

Have you compared the formats used by clojure-lsp and jdt.ls?

**Comment by joaotavora** [comment]
> Have you compared the formats used by clojure-lsp and jdt.ls?

No, have you? This format looks fine.  If someone else (jdt or hopefully LSP itslef) shows another format then Eglot will do some minimal translation. Same thing if Michael or the facts of code show that Clojurels format isn't suitable.

**Comment by dgutov** [comment]
> No, have you?

I'd have to install both to really do that. This handler looks pretty involved, though:

https://github.com/emacs-lsp/lsp-java/blob/master/lsp-java.el#L837-L877

**Comment by joaotavora** [comment]
yes, pretty involved.  Better stay away from it

**Comment by joaotavora** [comment]
OK, so to sum up, I think this

* is a low priority feature request for me personally (I don't have time right now), but anyone else can pick it up
* it should be implemented in Emacs itself, as a attributable package that Eglot can be made to depend on
* it should in theory be as simple as making that library add an element to `file-name-handler-alist`, with some supporting function. This is @dgutov 's idea number 1.
* the format to use shall be the one described here https://docs.oracle.com/javase/7/docs/api/java/net/JarURLConnection.html, unless some good reasons exist to deviate from it, in which case Eglot will translate from that format to Emacs's format

@Andre0991 since you seem to be interested in Lisp languages, you can try to develop this.  By scratching your itch, you'll help Eglot, Emacs and many others.

**Comment by dgutov** [comment]
Sounds like one hell of a first issue: lots of investigation and organizational stuff, not so much tech.

**Comment by joaotavora** [comment]
Yes, it's a bit ambitious as a first issue.  One should definitely start just experimenting briefly with `file-name-handler-alist` ( which as far as I know is documented) and then think about making the library.  It was just a suggestion for @Andre0991 , anyway.  I'm not saying I'm never going to pick this up myself, just not in the foreseeable future, so I was just registering those bullet points as a summary of what I think should be done after all this analysis.

**Comment by Andre0991** [comment]
Olá.

First, I need to amend my issue description.

I found out that there is this `config.edn` file that dictates some settings to `clojure-lsp`, including the URI format. Sorry about that - I didn't remember this file existed at all, I just realized that when mentioning the URI path thing to a coworker who is familiar with `clojure-lsp`.
This config file can exist on a per-project or globally in `~/.lsp/.config.edn`. It has the option `dependency-scheme`, whose default value is `zip`, but that can be changed to `jar`, which happens to be my case.

For more details, please see https://clojure-lsp.github.io/clojure-lsp/settings/.

On `dependency-scheme`, it says:

> How the dependencies should be linked, jar will make urls compatible with java's JarURLConnection. You can have the client make an lsp extension request of clojure/dependencyContents with the jar uri and the server will return the jar entry's contents. Similar to java clients.

I see that both [Calva](https://github.com/BetterThanTomorrow/calva/blob/756ab8c105333886dd26c61c786e8382b7f641be/src/lsp/main.ts#L23) and [lsp-mode](https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-clojure.el#L287) explicitely set this to `jar` in the initialization options.

If I don't set it to jar, `eglot` logs this:

```
[server-reply] (id:14) Tue Apr 13 20:52:11 2021:
(:jsonrpc "2.0" :id 14 :result
          (:uri "zipfile:///Users/andreperictavares/.m2/repository/org/clojure/tools.namespace/0.3.1/tools.namespace-0.3.1.jar::clojure/tools/namespace/find.clj" :range
                (:start
                 (:line 11 :character 2)
                 :end
                 (:line 11 :character 30))))
```

---

Also, I have a question, though I'm not sure if it's part of the scope of this issue.
Let's say the URI issue is solved and somehow Emacs knows how to open the thing in the jar.
Suppose I just did that by using `xref-find-definitions`.
Now, I'm wondering how this would impact `eglot` and the `clojure-lsp` server.
To be more specific: Will `xref-find-definitions` also work in this file, in case I need to navigate to yet another file in another jar?

---

I don't know if the points above impact anything you have discussed so far.

Finally: I don't know much `emacs-lisp`, but working on this issue looks very tempting. That said, I don't have much time right now and I see that I need to learn a lot of concepts. I'll try to do some experimenting with `file-name-handler-alist` on some weekend. That said if someone that is reading this knows how to do that and wants to tackle this issue, by all means, don't wait for me and do it.

**Comment by joaotavora** [comment]
> I am also not very proficient with emacs-lisp, and would love some feedback if anyone has the time.

Well, then, great effort.  I do spot a tiny bit of non-idiomatic Elisp code here and there, but nothing really serious. I guess you know Clojure, Elisp isn't so off.

I don't understand the entry point. How does one find a file in a `.jar`, does one just `C-x C-f` to it like if there jar were a directory? Anyway, from my cursory look this does seem suited to `clojure-mode.el`, for sure.  At any rate _not_ Eglot: except for the references to language servers and how to start them, Eglot is completely language-agostic.

**Comment by joaotavora** [comment]
> Not sure I understand this question. 

You ended up answering it.  I think that, with your code loaded, if you give `/path/to/library.jar::path/inside/jar/to/source.clj` to `C-x C-f` it will open `source.clj` inside the `jar`.  And the same will happen when `xref-find-definitions` tries to find it.

So it looks pretty good. Though on second thought, `jar`s aren't really Clojure-specific are they? So submitting to `clojure-mode` may not make much sense.  Also, jars are just zip files, aren't they? So do check if Emacs doesn't have some utilities similar to this one for zips that may also work for jars.   Else, maybe a new package `jar-utils` in GNU ELPA looks good.

**Comment by mainej** [comment]
@dannyfreeman Emacs already knows how to handle jars and their files. Try opening a jar file in your .m2 directory. When I do that, I end up in a file that looks like `/path/to/.m2/repository/rewrite-clj/rewrite-clj/0.6.1/rewrite-clj-0.6.1.jar:rewrite_clj/parser/core.clj`. Note the single colon separating the jar name and the file name. I wonder if `clojure-lsp` could be modified to return URIs of that format. (I've been helping maintain clojure-lsp lately, so I might be able to help with that ;))

**Comment by joaotavora** [comment]
Or maybe emacs facilities for handling jars could just learn to grok the double `::`?  Wouldn't that solve the problem as well?

**Comment by mainej** [comment]
To follow up on this … it appears that arc-mode.el provides [archive-mode](https://github.com/emacs-mirror/emacs/blob/55eabe96c92aaee336a7ed4cce4d5b4186c9eeeb/lisp/arc-mode.el#L651), which is a dired style view of an archive. Because jar files follow the zip file format, archive-find-type [classifies](https://github.com/emacs-mirror/emacs/blob/55eabe96c92aaee336a7ed4cce4d5b4186c9eeeb/lisp/arc-mode.el#L736) the jar as a zip. This gets translated in the mode line into “Zip-Archive”. From the dired view, you can navigate to a file.

So what I wrote above is slightly wrong... you can't just open a file within a jar. You have to open the jar first and then find a file within it.

That’s as far as I’ve gotten. I’m not sure yet how archive-mode unzips the file, or whether that’s something tools like eglot could hook into.

> Or maybe emacs facilities for handling jars could just learn to grok the double ::? Wouldn't that solve the problem as well?

@joaotavora that sounds ideal, although we're way over my head already.

**Comment by mainej** [comment]
> (archive-zip-extract jar source-file)

@dannyfreeman that's exactly what cider [does](https://github.com/clojure-emacs/cider/blob/20debc82696bdd5ce807618d02665b92a4274492/cider-common.el#L396) in `cider-find-file`. Thanks to @ericdallo for pointing that out.

So I'd say all signs are pointing to using `archive-zip-extract` from arc-mode.el to unzip jar files into temp buffers. Exactly how, where, and when to do that are open for debate. It'd be amazing to have it built into Emacs in `find-file`. That would have the broadest reach. But having it in eglot would be nice too, since all JVM languages would benefit from being able to open JAR files. Or perhaps it belongs in a package outside of eglot so that lsp-mode and cider can use it too.

**Comment by mainej** [comment]
A note on clojure-lsp...

As you've discussed there's a setting called `:dependency-scheme` which controls how clojure-lsp renders URIs.

There are two valid values `"zipfile"` and `"jar"`. For historical reasons `"zipfile"` is the default, although the recommended value is `"jar"` and many lsp clients set that as their own default.

Note that you might find documentation that suggests `:jar` (a keyword) and other invalid things. These are all equivalent to setting `"zipfile"`, which is admittedly horribly confusing. We've planned to fix those docs. Also note that we might change the default at some point. We may even remove `"zipfile"` entirely, since it's infrequently used and causes confusion. Both are reasons to set it to `"jar"` explicitly.

The URIs for `"zipfile"` look like
```
zipfile://<path-to-jar>::<path-to-entry>
```
An example is `zipfile:///some/path/some.jar::some/file.clj`. Note that the path-to-jar begins with a slash (so 3 slashes at the beginning) and that the separator is `::`.

The URIs for `"jar"` look like
```
jar:<uri-to-jar>!/<path-to-entry>
```
Here uri-to-jar is itself a uri, usually with the format `file://<path-to-jar>`. So, a full example is `jar:file:///some/path/some.jar!/some/file.clj`. Note that again we have 3 slashes, but the separator is `!/`.

You may be dismayed to see a URI in a URI. I agree, but direct your complaints to Java who [defined this style](https://docs.oracle.com/javase/7/docs/api/java/net/JarURLConnection.html). 🙄 And actually, since this is Java's preferred way of referencing its own jar files, ideally Emacs would understand this style too.

@dannyfreeman you're setting `:jar` but getting back `"zipfile"` style URIs. The fact that your regex searches for `::`, not `!/` confirms this. I recommend that you (and eglot) use `"jar"` so I'd suggest you update your setting and your regex.

**Comment by joaotavora** [comment]
> Would eglot maintainers be interested in a patch for double parsing the URIs with a jar scheme? If not, could providing the :dependency-scheme "zipfile" to clojure-lsp when starting the process be considered instead?

Actually, i think both options are reasonable. Can you submit two different patches for each option to bug-gnu-emacs@gnu.org, referencing this issue? (Eglot now lives in Emacs, if you haven't gathered, so your patch might also target other areas in Emacs that need tweaking) You can use the same email message for both patches, just make sure to clearly identify them as being alternatives to one another.

The patch with the initialization option can probably be done in `eglot-server-programs`.

I'd also like to understand if these patches to Emacs are enough to fix the issue completely from the user's perspective, or if some more code or extra package is needed after them.

**Comment by joaotavora** [comment]
> This only makes it so that https://github.com/joaotavora/eglot/issues/661#issuecomment-1287430939 capable of dealing with the jar style paths.

But hadn't we established earlier that there's already some code in Emacs itself which does more or less the same?

Regardless of your answer to the previous question, and imagining one of those patches in in place in `lisp/progmodes/eglot.el`, what is the full set of things must the user do/install to get find definitions for external dependencies?  Don't be afraid to state the obvious, like "install Emacs version XYZ", or "install upcoming Eglot ELPA package version XYZ2".  I just want to get the overall picture.

**Comment by joaotavora** [comment]
Fell free to answer the questions/continue discussion in the bug report where you propose the patches.

**Comment by abcdw** [comment]
@dannyfreeman Could you provide a link to the thread with patches, please?

**Comment by sw1nn** [comment]
@dannyfreeman fyi, I tried your patch to eglot + jarchive and it works for me to `xref-find-definitions` from source outside jar to source inside the jar, but if I then try to `xref-goto-definition` for some fn defined in the 'source in the jar', I don't find definitions, but rather a text match within the file. I realise this is all getting a bit inception, I guess this might require a bit more co-ordination between xref and eglot.

**Comment by mainej** [comment]
> if I then try to xref-find-definitions for some fn defined in the 'source in the jar', I don't find definitions

@ericdallo perhaps you can help @dannyfreeman with this. I know that lsp-mode is able to do the two-level navigation `project file -> dep file 1-> dep file 2` so perhaps you have some insight about how the temp buffers need to be managed to support this.

**Comment by joaotavora** [comment]
Are people here aware of eglot-extend-to-xref or eglot-xref-extend (can't
remember the name right now...)?

That's how "level 2" xref-find-definition is supposed to work in Eglot.
Whether just setting the flag to t works with the current patches is
another matter...

**Comment by abcdw** [comment]
@dannyfreeman Thank you! 

BTW, I packaged jarchive for guix:
https://git.sr.ht/~abcdw/rde/tree/90af100a4d70d7016261d39b91b6748768ac374b/rde/packages/emacs-xyz.scm#L330

**Comment by dgutov** [comment]
> In my mind, project.el should support adding jars as collections of source files just like it supports adding directories as collections of source files. Many years ago, Eclipse did this. You could add a jar as a library or a file as a library: it's just a different implementation detail.

Sounds like you want to advise `project-vc-external-roots-function`. Or change its whole value.

Or create an Eglot-specific project backend.

**Comment by joaotavora** [comment]
I'm going to answer this in Emacs's bug tracker https://lists.gnu.org/archive/html/bug-gnu-emacs/2022-10/msg02118.html. It's akward and unpractical to keep commenting in both places.

**Comment by joaotavora** [comment]
I was just registering the reason for closing the issue.  Don't worry, I'll CC you the next email.

**Comment by andreyorst** [comment]
sorry, what's the status of this? I see this issue is closed as completed, but the mailing-list thread suggests that the feature is not yet supported?

I'm considering migrating from lsp-mode to Eglot once this feature is implemented, but the status is a bit unclear.

**Comment by Andre0991** [comment]
Oh, indeed, I missed the newest messages.

Thank you so much for tackling this – I just installed `jarchive` and LSP+Clojure is 100% supported by Emacs now.

**Comment by pesterhazy** [comment]
FWIW, I just tried jarchive, and it doesn't fix the issue for me. I get an error like this:

```
Error in post-command-hook (#[0 "\303\304\301\242\305#\210\300\306!\205r\211q\210
?\205\307\310\311 \")\207" [#<buffer fs.cljc> (#0) eglot--managed-mode remove-hook post-command-hook nil buffer-live-p apply eglot--connect eglot--guess-contact] 4]): (file-missing "Setting current directory" "No such file or directory" "/Users/user/.m2/repository/babashka/fs/0.1.2/fs-0.1.2.jar::babashka/")
```
