### ISSUE TITLE
`completion-regexp-list` is not respected

### ISSUE THREAD

**Issue by jdtsmith** [joaotavora/eglot#725]
* Server used:               python-lsp-server
* Emacs version:             GNU Emacs 27.2 
* Operating system:          MacOS
* Eglot version:             20210901.917
* Eglot installation method:       package-install
* Using Doom:                No

The basic completion docs for `try-completion` (also applying to `test-completion`, `all-completions`, etc.) state (emphasis added):

> In addition, to be acceptable, a completion must also match all the
     regular expressions in ‘completion-regexp-list’.  (Unless
     COLLECTION is a function, **in which case that function has to handle
     ‘completion-regexp-list’ itself**.)

The [COLLECTION function](https://github.com/joaotavora/eglot/blob/122dbb9d6ef477c5c5f0351895652b825d6447de/eglot.el#L2357) provided by eglot does not appear to consider `completion-regexp-list`.  This variable is important for completion styles such as [orderless](https://github.com/oantolin/orderless), which put `completion-regexp-list` to heavy work for candidate refinement.  Since most in-built completion tables are obarrays, alists, hashes, etc., the issue really only pertains to programmed completion, such as in eglot. I have a small patch to the `proxies` lambda which implements this, and works well in my testing.  Let me know if you'd like to see a PR.   See also oantolin/orderless#78.  Thanks for eglot!

**Comment by nemethf** [comment]
In Emacs version 26.1, the docstring at the end of try-completion says: Additionally to this predicate, ‘completion-regexp-list’
is used to further constrain the set of candidates.  To me, this means that try-completion internally takes care of filtering candidates according to completion-regexp-list.   However, Eglot doesn't use all-completion.  Isn't that the root cause of this issue?

I'm guessing here, but appropriately changing cl-remove-if-not to all-completion after the "all-completion" comment might just fix the issue.
