### ISSUE TITLE
Enabling eglot in files outside current project after following xrefs

### ISSUE THREAD

**Issue by mkcms** [joaotavora/eglot#76]
When I find a definition outside current project, eglot is either not enabled or enabled, but using a different server. I'd like to have it enabled and using the same server where it came from, unless I explicitly started it with `eglot` or there was already a server managing this buffer started with `eglot-ensure`, but not in a transient project.

**Comment by joaotavora** [comment]
> When I find a definition outside current project

The solution here would be to teach `project.el` that the file you visited is actually in the same project that you came from.  Isn't that possible?

**Comment by joaotavora** [comment]
You could start by adding some `mkcms/try-to-find-related-java-project` to `project-find-functions`.  This would slightly abuse the semantics that a project is supposed to "contain" a file of the given buffer where you call `project-current`, but I don't see any problem in that.

At some point though , you would of course have to make a decision in `mkcms/try-to-find-related-java-project` as to which project to pick, because there may be more than one. Eventually that function may become `eglot-setup-finding-related-java-projects` which we add to `eglot.el` and suggest that users add to `java-mode-hook` just like we suggest to add `eglot-ensure` there.

Another interesting generic function is `project-external-roots`. In `project.el` "external roots" are defined thusly
```
It's the list of directories outside of the project that are
still related to it.  If the project deals with source code then,
depending on the languages used, this list should include the
headers search path, load path, class path, and so on.

The rule of thumb for whether to include a directory here, and
not in `project-roots', is whether its contents are meant to be
edited together with the rest of the project.
```

This seems to fit nicely with the `/usr/include` example, but the implementation is kinda sketchy (still?). Still, if you could configure them (perhaps using `project-vc-external-roots-function`) then `eglot-setup-finding-related-java-projects`could possibly become `eglot-setup-search-for-projects`, and in this case we could make it a defcustom.

Am I explaining myself here?

**Comment by MaskRay** [comment]
For references outside of the project, the action itself has the attribute of "dynamic binding".

What I did in lsp-ui is to populate the current workspace information to the newly opened buffer

https://github.com/emacs-lsp/lsp-ui/blob/master/lsp-ui-peek.el#L472

```elisp
(defun lsp-ui-peek--goto-xref (&optional x other-window)
.......
            (unless lsp--cur-workspace
              (setq lsp--cur-workspace current-workspace))
            (unless lsp-mode
              (lsp-mode 1)
              (lsp-on-open))
```

```c++
// hit textDocument/definition on the include line
#include <stdio.h>
```

`/usr/include/stdio.h` will be opened (cquery would fail to do so if it was on Arch Linux, details omitted). 

I have `  (setq projectile-require-project-root t)`, so that `(projectile-project-root)` will return `nil`. Then ` lsp--cur-workspace` of the current buffer will be populated to the new one.

**Comment by mkcms** [comment]
> Why should eglot.el should bother configuring `project-external-roots`?

I meant that I can modify `project-external-roots` myself, outside of eglot, when I want to enable eglot in directories outside my current project after following xrefs.
I don't think this is a perfect solution though, because it requires that I know all the files that my project depends on (or rather, their directories)

**Comment by joaotavora** [comment]
> I don't think this is a perfect solution though, because it requires that I know all the files that my project depends on (or rather, their directories)

Yes, but since it is a generic function, a sufficiently smart implementation could discover this right?

**Comment by mkcms** [comment]
> Yes, but since it is a generic function, a sufficiently smart implementation could discover this right?

Yes, sufficiently smart. But I can't imagine how much pain it would be to setup.
For example, for c++ projects, I would actually have to run the compiler to get the exact include directories, or for python I would have to start the interpreter to get the load path, etc. Doing these things in a cross-platform way is impossible. The language server already knows about all these paths though.

**Comment by joaotavora** [comment]
> The language server already knows about all these paths though.

Can we request them after starting the server and use that to feed our `project-external-roots` implementation?

**Comment by mkcms** [comment]
> Can we request them after starting the server and use that to feed our `project-external-roots` implementation?

There's no request method AFAICS. But what I was thinking is using `xref-after-jump-hook` to detect when eglot opened a file in some directory, then adding that directory to `project-external-roots`.

**Comment by joaotavora** [comment]
> There's no request method AFAICS. But what I was thinking is using xref-after-jump-hook to detect when eglot opened a file in some directory, then adding that directory to project-external-roots

You're always free to try of course, but eventually one would have to solve the following problems, or at least a part of the following problems:

* how are you going to tell the function that you put in `xref-after-jump-hook` that you came from a particular `eglot-lsp-server` instance? A variable? Keep in mind that the `*xref*` buffer can sometimes be used and sometiems not, and it can linger on for a while, so it would have to be a buffer-local variable of that specific buffer.  But how to set it there?  All you have is `xref--xref-buffer-mode-hook` . 

* when you land in a file and you know the `eglot-lsp-server` what are you going to do? I think it is too late by the time of `xref-after-jump-hook`.  You want the external roots of the `eglot-lsp-server`s' project to be correctly setup so that by the time you find that file, `eglot--maybe-activate-editing-mode` does its job and eglot is all setup there.

* Then you have the problem of some directories (some "roots") being shared by more than one project, which means they are shared by more than one server.  I say we warn the user, at the most and only if it's easy to tell what happened, and don't even try to tackle this problem for now.

I think the best way to solve this is to greedily and collect directories to feed `project-external-roots` as soon as we get them from the server like in `xref-backend-definitions` and, if they are outside `project-roots`, save them in the server as `external-roots`.  Then, in a global `:around` method for `project-external-roots` try to match the `PROJECT` argument to one of our servers (using `eglot--servers-by-project`) and return those dirs along with whatever `call-next-method` returns.

Now `project.el` and the usual Eglot machinery should hopefully do the rest so that when you go to an xref everything should be setup neatly. Unfortunately, it's not enough because I don't think `project-current` considers external roots.  So we probably have to add a global `eglot--find-project` to `project-find-functions` (desirably at the end)  that returns the matching project, or nil.

Makes sense?

**Comment by MaskRay** [comment]
See https://github.com/emacs-lsp/lsp-mode/pull/474 and Riatre's comment below.

Some files (`/usr/include/stdio.h`) are in an indeterminate state and such directories may not even be known beforehand. I currently rely on a hack in lsp-ui-peek https://github.com/emacs-lsp/lsp-ui/commit/2300e94a9a1d953b2f5c436c5f915da31ca2fb8b

**Comment by joaotavora** [comment]
@maskray, I have little time to study your references right now, but tell me: eventually, when returning uri's for definitions/references, a real existing file is referenced right? My plan is to collect those directories then, and then let eglot's usual mechanism do its thing. I don't want to me with workspaces or folders at all. Perhaps I'm being naive here: we'll see...

**Comment by mkcms** [comment]
@joaotavora 

>     * how are you going to tell the function that you put in `xref-after-jump-hook` that you came from a particular `eglot-lsp-server` instance? A variable?

A special `xref-item` which holds the server instance. I believe it's already possible to do that by extending `xref-item`.
Obviously we would have to ask Emacs developers to provide a way to get the item which caused the current jump. There already is private a variable which holds that information, `xref--current-item`.

>     * when you land in a file and you know the `eglot-lsp-server` what are you going to do? I think it is too late by the time of `xref-after-jump-hook`.  You want the external roots of the `eglot-lsp-server`s' project to be correctly setup so that by the time you find that file, `eglot--maybe-activate-editing-mode` does its job and eglot is all setup there.

Indeed, that is a problem. Maybe extending `eglot-ensure` so that it can detect if the current buffer was created for an xref jump is possible. We could make `eglot-ensure` actually run after the current command. By that time, surely `xref-after-jump-hook` would have ran. Although this is hacky and changes the current behavior of that function.

>     * Then you have the problem of some directories (some "roots") being shared by more than one project, which means they are shared by more than one server.  I say we warn the user, at the most and only if it's easy to tell what happened, and don't even try to tackle this problem for now.

We might also mark the buffer->server relation as "transient" in buffers which are outside the main project root. When a buffer is in that state, `M-x eglot` wouldn't warn the user that there is an existing connection. It would just disconnect current buffer from the existing server (keeping the server alive in other buffers), and connect normally.

All in all, I don't know if what I'm suggesting is possible or if it even makes sense. I would have to implement it first to find out.

**Comment by vconcat** [comment]
I have tried this branch, tested with two golang projects which share a library.

It works, when in project A and use `xref-find-definition` to goto the library file, there are no other server process created for it(which is what I wished).

When in project B and xref to same library file, it just go to the previous buffer which managed by project A.

But I dont' know whether this may lead to some unexpected problem.

**Comment by joaotavora** [comment]
I had completely forgotten about this.

Did you rebase on top of the newest master?  Can you keep on testing for a while?

**Comment by joaotavora** [comment]
> I just check the doc of project.el, maybe the my request can be archived by custome project-external-roots?

Maybe.

The branch is ancient, it's doesn't rebase cleanly on top of `eglot.el` anymore.  But it's not very complex either, so it should be possible to re-do it.  I think I follow its 2+ year old logic, still.

But leveraging `project-external-roots` would be cleaner, indeed.

**Comment by vconcat** [comment]
> The branch is ancient, it's doesn't rebase cleanly on top of `eglot.el` anymore. But it's not very complex either, so it should be possible to re-do it. I think I follow its 2+ year old logic, still.

I will try to test this.

**Comment by vconcat** [comment]
I had tried `project-external-roots` with below configuration:
```
(setq make-backup-files nil
      auto-save-default nil)

(add-to-list 'load-path (expand-file-name "~/.emacs.d/straight/repos/eglot"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/straight/repos/project"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/straight/repos/go-mode.el"))

(require 'go-mode)
(require 'eglot)

(add-hook 'go-mode-hook 'eglot-ensure)

(require 'project)

(defun go-library-paths ()
  (list "~/go/pkg"))

(defun go-project-external-roots ()
  (setq-local project-vc-external-roots-function 'go-library-paths))

(add-hook 'go-mode-hook 'go-project-external-roots)
```

When I xref to a library file, eglot start aother `gopls` process for it.

**Comment by vconcat** [comment]
Finally I use below hacking to reduce the number of process `gopls` may spawned.

```elisp
  (defvar go-library-project-root (make-temp-file "go-library-" t))

  (defvar go-library-directories '("~/go/pkg"))

  (defun project-try-go-library (dir)
    (when (cl-some (apply-partially 'f-descendant-of-p dir) go-library-directories)
      (cons 'go-library go-library-project-root)))
  
  (defmethod project-root ((project (head go-library)))
    (cdr project))

  (add-hook 'project-find-functions 'project-try-go-library)
```

**Comment by vconcat** [comment]
```elisp
    (defvar go-library-directories '("~/go/pkg"))

    (defvar go-library-project-root (f-join (temporary-file-directory) "eglot-library-projects/go-library"))

    (defun go-setup-library-project-root ()
      (let* ((root go-library-project-root)
             (project-file (concat root "/go.mod")))
        (unless (file-exists-p root)
          (make-directory root 'parents))
        (unless (file-exists-p project-file)
          (with-temp-file project-file
            (insert "module go-library\n")))))

    (go-setup-library-project-root)

    (defun project-try-go-library (dir)
      (when (or
             (f-same-p dir go-library-project-root)
             (cl-some (apply-partially 'f-descendant-of-p dir) go-library-directories))
        (cons 'go-library go-library-project-root)))

    (cl-defmethod project-root ((project (head go-library)))
      (cdr project))

    (cl-defmethod project-external-roots ((project (head go-library)))
      go-library-directories)

    ;; (cl-defmethod project-files ((project (head go-library)))
    ;;   nil)

    (add-hook 'project-find-functions 'project-try-go-library)
```

**Comment by cmm** [comment]
A problem with `project-external-roots` is that by itself it maps a project to its external roots, but there is no existing logic to go the other way around, and the latter is what is actually interesting.

That is, to use it for finding the project given, say, a path under "/usr/include/", you need also:
- To make sure you store a map from "external" path prefixes to your "main" project(s) -- you can add a function that populates the map (from `project-external-roots`), to `eglot-connect-hook`
- To add a function to `project-find-functions` that uses above map

This also presupposes:
-  That you have a way to statically enumerate all (possible) external project roots
-  That you are OK with having just one "global" or "current" project with respect to possibly-shared "library" code (I for one am, but this is definitely a limitation)

A solution that works on-demand by riding on (say) xref would be much better, needless to say.

**Comment by dgutov** [comment]
> A problem with project-external-roots is that by itself it maps a project to its external roots, but there is no existing logic to go the other way around, and the latter is what is actually interesting

Is that really a problem with it, and not with the task at hand? There is no logical way to go from `/usr/include/` to whatever project you have been editing previously.

So yes, you can store some additional information, e.g. from which projects you had jumped to specific external roots. Or just do a linear search across current project managed by Eglot, to find the first one that refers to the current external directory.

> ...
> To add a function to project-find-functions that uses above map

I recommend you don't try to alter what project.el thinks is the "current project", and instead create an Eglot-specific wrapper for it that uses the above information.

**Comment by cmm** [comment]
> don't try to alter what project.el thinks is the "current project"

Yes, I came to the same conclusion, just not in time :)
Was just riffing on the suggestions in this tread, and, well.  Then again, eglot is the only vector through which I'm even _aware_ of project.el (unless projectile uses it internally or extends it?)

**Comment by dgutov** [comment]
> unless projectile uses it internally or extends it?

Someday it will: https://github.com/bbatsov/projectile/issues/1591

But you can use project-related commands without Projectile. See `C-x p C-h` with the latest version of project.el installed.

> (Also, eglot maps directories to servers using (project-current), so there's also that to consider)

That's why I mentioned creating a wrapper.

**Comment by cmm** [comment]
@joaotavora I've rebased your provisional patch on current master here: https://github.com/joaotavora/eglot/pull/686

It works!  Perhaps it could even be, *gasp*, mergeable if put under an option?  Like `eglot-sprawl-across-xrefs`, or something?

**Comment by joaotavora** [comment]
Hmm, did I write that? Maybe... Can you help me explain back to me how my code works, this idiot João from the past didn't leave many comments...

**Comment by cmm** [comment]
a little clearer now, I hope
