### ISSUE TITLE
Trigger completion after special char like `.`, `::`,...

### ISSUE THREAD

**Issue by mssdvd** [joaotavora/eglot#80]
Is it possible to trigger the completion after special chars like `.` or `::` have been typed?
Currently `company` is triggered only when `company-minimum-prefix-lenght` is reached and when it is called directly by the user.

**Comment by jojojames** [comment]
I was just looking at the same thing!

I think eglot is using company-capf and the change would either be in one of eglot <-> company-capf <-> company.

You can work around it in company-capf by always returning a cons cell with t along with the prefix. (Of course that might not be desirable for other backends that utilize company-capf but don't have ./->/:: syntax.

Here's my workaround so far...
```
(defun company-capf-advice (f &rest args)
  "Look for \"\\.\\|->\\|::\".

Return prefix that bypasses `company-minimum-prefix-length' if found."
  (if (not (eq (nth 0 args) 'prefix))
      (apply f args)
    (let ((result (apply f args)))
      (if (eq result 'stop)
          result
        (if (save-excursion
              (forward-char -1)
              (looking-at-p "\\.\\|->\\|::"))
            (if (consp result)
                (progn (setcdr result '(t)) result)
              (cons result t))
          result)))))

(advice-add 'company-capf :around 'company-capf-advice)

```

This looks like something that seems like it can be at the company layer but seeing how some of the backends are written (company-clang), I think the intention was probably to handle it at the backend layer.

```
;; company-clang
(defun company-clang--prefix ()
  (if company-clang-begin-after-member-access
      (company-grab-symbol-cons "\\.\\|->\\|::" 2)
    (company-grab-symbol)))
```

I'm not sure how eglot would provide company-capf with the right data since I haven't looked at how it's providing that data to company-capf but it might be doable at the eglot layer too.

**Comment by joaotavora** [comment]
Can you try the experimental commit I pushed to the `scratch/80-trigger-chars` branch?

**Comment by jojojames** [comment]
@joaotavora Nice, that works for me from short testing with pyls and kotlin-language-server.

**Comment by joaotavora** [comment]
All it does is trigger completion manually when you've just inserted a character and formed one of the strings that the spec designates as "triggerCharacters".  I don't know if there's anything more involved. Also, I don't think I'll make this feature the default, as it seems a bit intrusive.

**Comment by jojojames** [comment]
Hmnn yeah, I think that implementation is a little more intrusive than hooking it into company's 'prefix argument..

**Comment by joaotavora** [comment]
> Hmnn yeah, I think that implementation is a little more intrusive than hooking it into company's 'prefix argument..

Why? In what way?

**Comment by fbergroth** [comment]
There's an easier way to implement this. You can pass `:company-prefix-length t` (note that I believe it has to be `t` and not just non-nil) in `eglot-completion-at-point` if you want to trigger a completion.

So something like (untested):
```
:company-prefix-length (and (cl-some #'looking-back
                                     (mapcar #'regexp-quote
                                             (eglot--server-capable :completionProvider
                                                                    :triggerCharacters)))
                            t)
```

**Comment by mssdvd** [comment]
@joaotavora it works for me with rls.

**Comment by joaotavora** [comment]
> There's an easier way to implement this. 

Indeed, that's much easier. Thanks everybody.
