### ISSUE TITLE
Non-prefix completion broken

### ISSUE THREAD

**Issue by dgutov** [joaotavora/eglot#812]
* Server used:              clangd, sample file outside of a project
* Emacs version:            GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2022-01-07
* Operating system:          Ubuntu 20.04.3 LTS
* Eglot version:             20220116.1317
* Eglot installation method:       package.el
* Using Doom:                No

Visit `test.cpp` (contents are not important), move point inside `int main() {`, `M-x eglot`, `M-x company-mode`.

Type `cl`. See completions:

  **cl**ass
  de**cl**type
  thread-lo**c**a**l**

(that is the entire list, which is expected)

Type `clt`. See no completions. Or type `loc`, or etc.

Same with `M-x completion-at-point`.

**Comment by joaotavora** [comment]
In #807 whence this comes [you state](https://github.com/joaotavora/eglot/discussions/807#discussioncomment-1983402) this comes from commit 670ee61169419e8e82b0bb115338bd5abbc44640.

What is the result of your two experiments (`cl` and `clt` ) when that one-line commit is reverted?

**Comment by dgutov** [comment]
> What is the result of your two experiments (cl and clt ) when that one-line commit is reverted?

`cl`: same.

`clt`: one completion,

de**clt**ype

**Comment by dgutov** [comment]
Or for `la`:

c**la**ss
vo**la**tile
f**l**o**a**t
...

That also doesn't work with `:exclusive no`.

**Comment by joaotavora** [comment]
It's very odd that `cl`  begets `thread-local` correctly, but not `decltype`.  Thanks, @dgutov, for the intelligible recipe.  

Presumably the problem is independent of frontend.  Therefore, whoever analyses this should first test with `M-x completion-at-point`, not company.   I'm also presuming `emacs -Q`  or close equivalent was used.

**Comment by dgutov** [comment]
> It's very odd that cl begets thread-local correctly, but not decltype.

It is very consistent with the FIXME comment that I cited.

**Comment by joaotavora** [comment]
@gmbuell in the pull request #770 did you test any kind of "non-prefix" completions like these?

**Comment by dgutov** [comment]
What that code does is sets `res` to nil if there are no prefix completions in the completion table for the current input.

There exists a proper prefix completion for `cl`. There are none for `clt` or `la`.

**Comment by joaotavora** [comment]
Aha! I see, thanks

**Comment by joaotavora** [comment]
This is an Emacs issue, but maybe we should revert the #770 commit until it is fixed (which since `minibuffer.el`  isn't a ELPA package, will be quite long, unfortunately).  The fix in Emacs would seem to be to do the relevant lisp test considering the completion styles currently active.  Or maybe at least try `flex`  in there, hacky but not particularly hackier then the current solution.

**Comment by joaotavora** [comment]
I'm completely away from that code, but it seems one could use a completion-style-aware `try-completion` test for the single `decltype`  non-prefix completion that you list in your "bad" example.  I can't imagine how that operation could be very expensive, at least not with the `flex` completion style I developed (and probably others).

**Comment by dgutov** [comment]
`try-completion` can be fast in theory, but the act of choosing the proper completion style to use involves matching the whole set of completions, often with multiple styles.

I'm not sure simply choosing `flex` there is the answer. It will likely cause other edge cases.

**Comment by dgutov** [comment]
> Presumably the style has already been chosen when we called the completion function.

I don't think it was. That `try-completion` call will often be the first time that the completion table is searched.

> As for the second case of speculation... it's just speculation. But hardcoding flex there seems no worse than the current heuristic.

It's just not a proper fix. OK, you hardcode `flex`. If the user's actual completion style is more conservative (e.g. they only want prefix completion), `:exlusive no` will fail to work in a number of contexts but will mysteriously work in others.

If the user's completion style is more lax (e.g. `orderless`), they will get a similar problem to the one I reported here.

**Comment by joaotavora** [comment]
> I don't think it was. That try-completion call will often be the first time that the completion table is searched.

I assumed that the set being searched with `try-completion`  had already been narrowed down.  Sure it isn't?  Not that it matters much: it doesn't make much of a difference, the important thing is that that work must be performed anyway.  So if this is the first time the completion style is decided on, let this event record it so that it isn't performed again.  I don't care how "expensive" it is, as long as the whole process is not _more_l expensive than it could be.

> It's just not a proper fix. 

Never said it was.  The current behavior is a hack, I was speculating this could be a _better_ hack, subject to testing. IOW I presumed it get much more broken than what it currently is,

**Comment by joaotavora** [comment]
@skangas If you're following this, regardless of the Emacs-side fix, if any,  think we have to revert the `:exclusive no` commit.  I guess there was a reason I hadn't heard of that :-)

**Comment by gmbuell** [comment]
> @gmbuell in the pull request #770 did you test any kind of "non-prefix" completions like these?

I never tried any non-prefix completion with company. Sorry for breaking things! I personally use orderless but the way I trigger my completions, it always begins from a prefix completion and gets moved to the minibuffer where subsequent narrowing doesn't cause eglot to update the completion results.

**Comment by joaotavora** [comment]
ah, interesting.  Thanks @gmbuell

**Comment by dgutov** [comment]
> I assumed that the set being searched with try-completion had already been narrowed down. Sure it isn't?

Depends on the completion source. It's one of those things that sound good on paper (lazy computations, y'all!), but end up bringing uncertainty and complexity with it.

>  Not that it matters much: it doesn't make much of a difference, the important thing is that that work must be performed anyway. So if this is the first time the completion style is decided on, let this event record it so that it isn't performed again. I don't care how "expensive" it is, as long as the whole process is not _more_l expensive than it could be.

I'm assuming it calls `try-completion` rather than `completion-try-completion` solely in order to make it faster. But caching the result might not be trivial to implement too, though that's probably doable one way or another.

It will also bring the cost of `(company-capf 'prefix)` up a few orders of magnitude, making features infeasible (like `company-sort-by-occurrence`).

> Never said it was. The current behavior is a hack, I was speculating this could be a better hack, subject to testing. IOW I presumed it get much more broken than what it currently is,

When the behavior is more subtly broken, it's also harder to pinpoint/reproduce/report/fix. Those situations are annoying on a very different level.

**Comment by monnier** [comment]
> @skangas If you're following this, regardless of the Emacs-side fix, if any,
> think we have to revert the `:exclusive no` commit.  I guess there was
> a reason I hadn't heard of that :-)

`:exclusive no` is a hideous hack from which you want to stay away as
much as possible, yes.

I don't think fixing it is a good idea either.
Instead is should be replaced by ways to combine several CAPFs into one.

The idea of "use completion-table 2 is completion-table 1 doesn't give
any useful result" is not meaningful in general: it can work great for
specific circumstances (typically when using restrictive completion
styles), but it clearly won't give any useful result when using
a completion style that always matches everything and relies on sorting
instead of filtering.

So how to combine various CAPFs in a useful way depends on the
completion style that are in use (as well as on other things like the
specific CAPFs involved, of course).


        Stefan

**Comment by jdtsmith** [comment]
I'm sure @minad has thoughts on this, since his [cape](https://github.com/minad/cape) package has the power to combine arbitrary CAPF's (even the unwilling), and his corfu UI [patches](https://github.com/minad/corfu/issues/9#issuecomment-960530380) the `:exclusive no` FIXME code in question.

**Comment by skangas** [comment]
> @skangas If you're following this, regardless of the Emacs-side fix, if any, think we have to revert the `:exclusive no` commit.

Yes, this seems like the correct thing to do here.
