### ISSUE TITLE
could eglot work with remote project?

### ISSUE THREAD

**Issue by zhongweiy** [joaotavora/eglot#84]
hi,
Say a project is on a remote raspberry pi, I have emacs installed on local desktop. When the project file is opened by the desktop emacs (say using tramp), can I get the open file indexed? 

Specificly, the project is a cpp project, the toolchain is only availabe on the remote pi. So the lsp server is better running on the remote pi. Can I get it work by eglot? 

Thanks!

**Comment by joaotavora** [comment]
Hi, this is a very good question.

> When the project file is opened by the desktop emacs (say using tramp), can I get the open file indexed?

Yes, I suppose so. Although it depends on how the server interprets the resulting file URLs. Eglot could, if the spec allows it (or even if it doesn't) implement a customization point for this.
 
> So the lsp server is better running on the remote pi. 

You can, assuming you have TCP/IP on the pi and start the server with this option.  See the docstring of `eglot-server-programs` for details.

**Comment by zhongweiy** [comment]
Thanks! I'll give a try.

**Comment by slippycheeze** [comment]
FWIW, I'd be ... quite in favor, shall we say, of this happening.  For "local", as in stdio style, servers, switching to just using `start-file-process` instead of `start-process` would be sufficient; interpreting the filenames reported as `(expand-file-name FROM-SERVER default-directory)` in the file buffer should work to get a tramp-suitable name for them -- or you can use `file-remote-p` on the buffer filename to get a "truthy" value that is the remote host prefix.  (eg: for tramp `/ssh:example.com:~/src` that'd return `/ssh:example.com:`, which you can paste to the front of an absolute remote path.

I'm glad to hear you are open to the idea, as depending how things go, I may end up with submittable patches; do you require confirmation of FSF contribution papers, or another agreement for them?

Please do not take this as any sort of promise about when, or if, I will do anything, though. :/

**Comment by joaotavora** [comment]
> switching to just using start-file-process instead of start-process 

This comment made me realize that this is better implemented in Emacs's jsonrpc.el, rather than in eglot.el (although it could be experimentally implemented in eglot).

> do you require confirmation of FSF contribution papers,

I require that you start the copyright paperwork process, but you can contribute before you get the official confirmation.

**Comment by zhongweiy** [comment]
@joaotavora 

> Although it depends on how the server interprets the resulting file URLs. Eglot could, if the spec allows it (or even if it doesn't) implement a customization point for this.

By following your suggestion, I took a try by providing a LSP remote server (a Cquery server) to Eglot and converting the tramp file URL to local file URL back and forth. And it works with my ugly [hacking patch to Eglot.](https://github.com/zhongweiy/eglot/commit/508245c66575af138fb651174ce3cba46fd9b2ee)

I have not tried the approach @slippycheeze mentioned (start the Cquery server by `start-file-process` seems much more convenient.)

Here are some details:

1. Get Cquery installed on my remote server (192.168.1.50). And run it by `nc -l -p 5010 -e cquery` to redirect stdout to socket.
2. Open a cpp file in the remote server by the local desktop Emacs by tramp ssh. And start the Eglot with server: 192.168.1.50:5010. Done.
